## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.7.1


## Introduction to Tensors

Link: https://docs.pytorch.org/docs/stable/tensors.html

### Creating tensors

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# matrix
matrix = torch.tensor([[7, 8], 
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
matrix.ndim

2

In [11]:
matrix.shape

torch.Size([2, 2])

In [12]:
matrix[0]

tensor([7, 8])

In [13]:
matrix[1]

tensor([ 9, 10])

In [14]:
# tensor
tensor = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [15]:
tensor.ndim

3

In [16]:
tensor.shape

torch.Size([1, 3, 3])

In [17]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [18]:
tensor[0][1]

tensor([4, 5, 6])

In [19]:
tensor[0][1][2]

tensor(6)

### Random tensors

In [23]:
# Create a random tensor of size / shape (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2055, 0.7716, 0.1860, 0.3704],
        [0.8767, 0.4654, 0.9135, 0.3334],
        [0.1460, 0.9450, 0.0264, 0.3212]])

In [25]:
random_tensor.ndim

2

In [26]:
random_tensor = torch.rand(3, 3, 3)
random_tensor

tensor([[[0.3308, 0.4211, 0.9933],
         [0.1862, 0.5777, 0.3840],
         [0.8937, 0.9038, 0.1769]],

        [[0.4536, 0.0347, 0.8635],
         [0.7910, 0.0271, 0.0627],
         [0.7379, 0.5559, 0.0989]],

        [[0.9127, 0.6145, 0.6815],
         [0.3308, 0.8223, 0.6634],
         [0.6535, 0.5382, 0.1116]]])

In [31]:
torch.rand(size=(1, 2, 3))

tensor([[[0.7362, 0.3195, 0.6442],
         [0.1223, 0.7583, 0.1941]]])

In [30]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [38]:
random_tensor = torch.rand(size=(3, 4))
random_tensor

tensor([[0.6986, 0.8931, 0.7225, 0.7798],
        [0.8603, 0.5302, 0.7339, 0.8332],
        [0.1854, 0.8132, 0.4536, 0.9793]])

In [ ]:
# tensor of zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [40]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [42]:
# tensor of ones
ones = torch.ones(size=(3, 4))

In [43]:
ones.dtype

torch.float32

In [44]:
ones * random_tensor

tensor([[0.6986, 0.8931, 0.7225, 0.7798],
        [0.8603, 0.5302, 0.7339, 0.8332],
        [0.1854, 0.8132, 0.4536, 0.9793]])

### Creating a range of tensors and tensors-like

In [51]:
torch.range(2, 8)

/var/folders/zd/7ryz379j2dz9shhk8m8k4zx40000gn/T/ipykernel_54383/616276269.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(2, 8)


tensor([2., 3., 4., 5., 6., 7., 8.])

In [50]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
one_to_ten = torch.arange(1, 11)

In [55]:
torch.arange(start=0, end=1000, step=99)

tensor([  0,  99, 198, 297, 396, 495, 594, 693, 792, 891, 990])

In [59]:
ten_zeres = torch.zeros_like(input=one_to_ten)
ten_zeres

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [ ]:
float_32_tensor = torch.tensor([3.0 , 6.0, 9.0], 
                               dtype=torch.float32)
float_32_tensor.dtype

torch.float32

In [66]:
float_16_tensor = torch.tensor([3.0 , 6.0, 9.0], 
                               dtype=torch.float16, # datatype of tensor
                               device="mps",
                               requires_grad=False)
float_16_tensor.dtype

torch.float16

In [69]:
float_64_tensor = float_32_tensor.type(torch.float64)
float_64_tensor

tensor([3., 6., 9.], dtype=torch.float64)

In [82]:
float_16_tensor.shape, float_16_tensor.device, float_16_tensor.dtype

(torch.Size([3]), device(type='mps', index=0), torch.float16)

In [71]:
float_64_tensor * float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float64)

In [72]:
float_32_tensor * float_64_tensor

tensor([ 9., 36., 81.], dtype=torch.float64)

In [74]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [75]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Manipulating tensors

In [84]:
a = torch.rand(size=(3, 3))
b = torch.rand(size=(3, 3))

In [85]:
a

tensor([[0.2077, 0.7796, 0.1493],
        [0.2571, 0.6442, 0.6639],
        [0.5323, 0.1965, 0.3612]])

In [86]:
b

tensor([[0.6208, 0.6377, 0.6728],
        [0.1550, 0.6941, 0.8001],
        [0.6331, 0.4480, 0.6835]])

In [93]:
a + 20

tensor([[20.2077, 20.7796, 20.1493],
        [20.2571, 20.6442, 20.6639],
        [20.5323, 20.1965, 20.3612]])

In [99]:
torch.add(a, 10)

tensor([[10.2077, 10.7796, 10.1493],
        [10.2571, 10.6442, 10.6639],
        [10.5323, 10.1965, 10.3612]])

In [87]:
a + b

tensor([[0.8286, 1.4173, 0.8221],
        [0.4121, 1.3382, 1.4640],
        [1.1654, 0.6445, 1.0448]])

In [94]:
a - 10

tensor([[-9.7923, -9.2204, -9.8507],
        [-9.7429, -9.3558, -9.3361],
        [-9.4677, -9.8035, -9.6388]])

In [98]:
torch.sub(a, 10)

tensor([[-9.7923, -9.2204, -9.8507],
        [-9.7429, -9.3558, -9.3361],
        [-9.4677, -9.8035, -9.6388]])

In [88]:
a - b

tensor([[-0.4131,  0.1419, -0.5235],
        [ 0.1021, -0.0499, -0.1362],
        [-0.1008, -0.2516, -0.3223]])

In [95]:
a * 10

tensor([[2.0774, 7.7959, 1.4932],
        [2.5711, 6.4415, 6.6391],
        [5.3228, 1.9646, 3.6124]])

In [97]:
torch.mul(a, 10)

tensor([[2.0774, 7.7959, 1.4932],
        [2.5711, 6.4415, 6.6391],
        [5.3228, 1.9646, 3.6124]])

In [89]:
a * b

tensor([[0.1290, 0.4971, 0.1005],
        [0.0399, 0.4471, 0.5312],
        [0.3370, 0.0880, 0.2469]])

In [96]:
a / 10

tensor([[0.0208, 0.0780, 0.0149],
        [0.0257, 0.0644, 0.0664],
        [0.0532, 0.0196, 0.0361]])

In [100]:
torch.div(a, 10)

tensor([[0.0208, 0.0780, 0.0149],
        [0.0257, 0.0644, 0.0664],
        [0.0532, 0.0196, 0.0361]])

In [90]:
a / b

tensor([[0.3346, 1.2225, 0.2219],
        [1.6588, 0.9281, 0.8298],
        [0.8407, 0.4385, 0.5285]])

In [106]:
torch.matmul(a, b)

tensor([[0.3443, 0.7405, 0.8656],
        [0.6798, 0.9085, 1.1422],
        [0.5896, 0.6376, 0.7622]])

In [91]:
a @ b

tensor([[0.3443, 0.7405, 0.8656],
        [0.6798, 0.9085, 1.1422],
        [0.5896, 0.6376, 0.7622]])

In [101]:
a ** 2

tensor([[0.0432, 0.6078, 0.0223],
        [0.0661, 0.4149, 0.4408],
        [0.2833, 0.0386, 0.1305]])

In [102]:
a ** (1 / 2)

tensor([[0.4558, 0.8829, 0.3864],
        [0.5071, 0.8026, 0.8148],
        [0.7296, 0.4432, 0.6010]])

In [107]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([1, 2, 3])

In [108]:
%%time
value = 0
for i in range(len(tensor)):
    value += a[i] + b[i]
value

CPU times: user 672 μs, sys: 1.56 ms, total: 2.23 ms
Wall time: 2.84 ms


tensor(2)

In [112]:
%%time
torch.matmul(a, b)

CPU times: user 65 μs, sys: 247 μs, total: 312 μs
Wall time: 2.94 ms


tensor(14)

In [111]:
%%time
a @ b

CPU times: user 110 μs, sys: 54 μs, total: 164 μs
Wall time: 162 μs


tensor(14)

In [113]:
torch.rand([3, 2]) @ torch.rand([3, 2])

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [114]:
torch.rand([3, 2]) @ torch.rand([2, 3])

tensor([[0.0356, 0.7247, 0.5514],
        [0.0715, 0.6257, 0.4373],
        [0.2841, 1.2637, 0.7503]])

In [115]:
torch.rand([2, 3]) @ torch.rand([3, 2])

tensor([[0.5916, 0.6099],
        [0.8692, 0.9737]])

In [120]:
a = torch.rand([4, 3])
a

tensor([[0.2579, 0.6954, 0.7692],
        [0.9505, 0.4404, 0.0285],
        [0.6914, 0.1466, 0.4204],
        [0.5003, 0.7245, 0.2820]])

In [125]:
b = a.T
b

tensor([[0.2579, 0.9505, 0.6914, 0.5003],
        [0.6954, 0.4404, 0.1466, 0.7245],
        [0.7692, 0.0285, 0.4204, 0.2820]])

In [123]:
a.shape, b.shape

(torch.Size([4, 3]), torch.Size([3, 4]))

In [124]:
b.T

tensor([[0.2579, 0.6954, 0.7692],
        [0.9505, 0.4404, 0.0285],
        [0.6914, 0.1466, 0.4204],
        [0.5003, 0.7245, 0.2820]])

In [128]:
torch.mm(a, a.T)

tensor([[1.1417, 0.5733, 0.6036, 0.8497],
        [0.5733, 1.0981, 0.7337, 0.8026],
        [0.6036, 0.7337, 0.6762, 0.5706],
        [0.8497, 0.8026, 0.5706, 0.8547]])