# 00. PyTorch Fundamentals Exercises

In [1]:
import torch

## 2. Create a random tensor with shape (7, 7).

In [ ]:
tensor_a = torch.rand(size=(7,7))

In [15]:
tensor_a

tensor([[0.4469, 0.1021, 0.8554, 0.9649, 0.7089, 0.2647, 0.7631],
        [0.5852, 0.2333, 0.6996, 0.8504, 0.0365, 0.9709, 0.3571],
        [0.2294, 0.8510, 0.1562, 0.3806, 0.5530, 0.3396, 0.7596],
        [0.7023, 0.7425, 0.6599, 0.9343, 0.0686, 0.1107, 0.1343],
        [0.4567, 0.3110, 0.2525, 0.3155, 0.8958, 0.8123, 0.7344],
        [0.8765, 0.1184, 0.3987, 0.7026, 0.4758, 0.8550, 0.9059],
        [0.0347, 0.6774, 0.1075, 0.3589, 0.8070, 0.6648, 0.3280]])

In [16]:
tensor_a.size(), tensor_a.shape, tensor_a.ndim

(torch.Size([7, 7]), torch.Size([7, 7]), 2)

## 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [ ]:
tensor_b = torch.rand(size=(1, 7))

In [20]:
tensor_b

tensor([[0.1887, 0.3809, 0.0920, 0.5083, 0.5110, 0.0978, 0.6093]])

In [22]:
tensor_a @ tensor_b.T

tensor([[1.5455],
        [1.0271],
        [1.3538],
        [1.0787],
        [1.3729],
        [1.4830],
        [1.1341]])

In [23]:
tensor_b @ tensor_a

tensor([[1.0255, 1.1471, 1.0112, 1.4645, 1.2294, 1.4110, 1.0819]])

## 4. Set the random seed to 0 and do 2 & 3 over again.

In [36]:
torch.manual_seed(42)
tensor_a = torch.rand(size=(7, 7))

torch.manual_seed(42)
tensor_b = torch.rand(size=(1, 7))

In [37]:
tensor_a @ tensor_b.T

tensor([[3.2618],
        [3.4084],
        [2.4866],
        [1.4525],
        [1.7079],
        [2.7291],
        [2.9204]])

In [38]:
tensor_b @ tensor_a

tensor([[3.0938, 2.7098, 2.7137, 2.4572, 2.0022, 2.6702, 1.5846]])

## 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

In [39]:
torch.cuda.manual_seed(42)

## 6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

In [48]:
torch.cuda.is_available()

False

In [51]:
torch.manual_seed(42)
tensor_a = torch.rand(size=(3, 2), device="mps")

torch.manual_seed(42)
tensor_b = torch.rand(size=(3, 4), device="mps")

In [52]:
tensor_a.device, tensor_a

(device(type='mps', index=0),
 tensor([[0.8172, 0.5881],
         [0.5581, 0.7691],
         [0.3394, 0.4560]], device='mps:0'))

In [53]:
tensor_b.device, tensor_b

(device(type='mps', index=0),
 tensor([[8.1718e-01, 5.8811e-01, 5.5805e-01, 7.6914e-01],
         [3.3936e-01, 4.5596e-01, 6.7508e-01, 4.4060e-04],
         [4.0876e-01, 1.7912e-01, 5.9732e-01, 8.4722e-01]], device='mps:0'))

## 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [55]:
tensor_a.T @ tensor_b

tensor([[0.9959, 0.7958, 1.0355, 0.9163],
        [0.9280, 0.7782, 1.1198, 0.8390]], device='mps:0')

In [59]:
tensor_b.T @ tensor_a

tensor([[0.9959, 0.9280],
        [0.7958, 0.7782],
        [1.0355, 1.1198],
        [0.9163, 0.8390]], device='mps:0')

## 8. Find the maximum and minimum values of the output of 7.

In [60]:
tensor_c = tensor_a.T @ tensor_b
tensor_d = tensor_b.T @ tensor_a

In [63]:
torch.min(tensor_c), tensor_d.min()

(tensor(0.7782, device='mps:0'), tensor(0.7782, device='mps:0'))

In [64]:
torch.max(tensor_c), tensor_d.max()

(tensor(1.1198, device='mps:0'), tensor(1.1198, device='mps:0'))

## 9. Find the maximum and minimum index values of the output of 7.

In [66]:
torch.argmin(tensor_c), tensor_d.argmin()

(tensor(5, device='mps:0'), tensor(3, device='mps:0'))

In [67]:
torch.argmax(tensor_d), tensor_d.argmax()

(tensor(5, device='mps:0'), tensor(5, device='mps:0'))

## 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [74]:
torch.manual_seed(7)
tensor = torch.rand(size=(1, 1, 1, 10))
tensor, tensor.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]))

In [75]:
new_tensor = tensor.squeeze()
new_tensor, new_tensor.shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))