# 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [137]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.7.1


## Introduction to Tensors

Link: https://docs.pytorch.org/docs/stable/tensors.html

### Creating tensors

In [138]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [139]:
scalar.ndim

0

In [140]:
scalar.item()

7

In [141]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [142]:
vector.ndim

1

In [143]:
vector.shape

torch.Size([2])

In [144]:
# matrix
matrix = torch.tensor([[7, 8],
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [145]:
matrix.ndim

2

In [146]:
matrix.shape

torch.Size([2, 2])

In [147]:
matrix[0]

tensor([7, 8])

In [148]:
matrix[1]

tensor([ 9, 10])

In [149]:
# tensor
tensor = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [150]:
tensor.ndim

3

In [151]:
tensor.shape

torch.Size([1, 3, 3])

In [152]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [153]:
tensor[0][1]

tensor([4, 5, 6])

In [154]:
tensor[0][1][2]

tensor(6)

### Random tensors

In [155]:
# Create a random tensor of size / shape (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

In [156]:
random_tensor.ndim

2

In [157]:
random_tensor = torch.rand(3, 3, 3)
random_tensor

tensor([[[0.1053, 0.2695, 0.3588],
         [0.1994, 0.5472, 0.0062],
         [0.9516, 0.0753, 0.8860]],

        [[0.5832, 0.3376, 0.8090],
         [0.5779, 0.9040, 0.5547],
         [0.3423, 0.6343, 0.3644]],

        [[0.7104, 0.9464, 0.7890],
         [0.2814, 0.7886, 0.5895],
         [0.7539, 0.1952, 0.0050]]])

In [158]:
torch.rand(size=(1, 2, 3))

tensor([[[0.3068, 0.1165, 0.9103],
         [0.6440, 0.7071, 0.6581]]])

In [159]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [160]:
random_tensor = torch.rand(size=(3, 4))
random_tensor

tensor([[0.7177, 0.6988, 0.5510, 0.2485],
        [0.8518, 0.0963, 0.1338, 0.2741],
        [0.6142, 0.8973, 0.3629, 0.1748]])

In [161]:
# tensor of zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [162]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [163]:
# tensor of ones
ones = torch.ones(size=(3, 4))

In [164]:
ones.dtype

torch.float32

In [165]:
ones * random_tensor

tensor([[0.7177, 0.6988, 0.5510, 0.2485],
        [0.8518, 0.0963, 0.1338, 0.2741],
        [0.6142, 0.8973, 0.3629, 0.1748]])

### Creating a range of tensors and tensors-like

In [166]:
torch.range(2, 8)

/var/folders/zd/7ryz379j2dz9shhk8m8k4zx40000gn/T/ipykernel_16459/616276269.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(2, 8)


tensor([2., 3., 4., 5., 6., 7., 8.])

In [167]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [168]:
one_to_ten = torch.arange(1, 11)

In [169]:
torch.arange(start=0, end=1000, step=99)

tensor([  0,  99, 198, 297, 396, 495, 594, 693, 792, 891, 990])

In [170]:
ten_zeres = torch.zeros_like(input=one_to_ten)
ten_zeres

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [171]:
float_32_tensor = torch.tensor([3.0 , 6.0, 9.0],
                               dtype=torch.float32)
float_32_tensor.dtype

torch.float32

In [172]:
float_16_tensor = torch.tensor([3.0 , 6.0, 9.0],
                               dtype=torch.float16, # datatype of tensor
                               device="mps",
                               requires_grad=False)
float_16_tensor.dtype

torch.float16

In [173]:
float_64_tensor = float_32_tensor.type(torch.float64)
float_64_tensor

tensor([3., 6., 9.], dtype=torch.float64)

In [174]:
float_16_tensor.shape, float_16_tensor.device, float_16_tensor.dtype

(torch.Size([3]), device(type='mps', index=0), torch.float16)

In [175]:
float_64_tensor * float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float64)

In [176]:
float_32_tensor * float_64_tensor

tensor([ 9., 36., 81.], dtype=torch.float64)

In [177]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [178]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Manipulating tensors

In [179]:
a = torch.rand(size=(3, 3))
b = torch.rand(size=(3, 3))

In [180]:
a

tensor([[0.2401, 0.5457, 0.7303],
        [0.5268, 0.6694, 0.3213],
        [0.4008, 0.2892, 0.9977]])

In [181]:
b

tensor([[0.6649, 0.5646, 0.9323],
        [0.4621, 0.4027, 0.1680],
        [0.1170, 0.5063, 0.6061]])

In [182]:
a + 20

tensor([[20.2401, 20.5457, 20.7303],
        [20.5268, 20.6694, 20.3213],
        [20.4008, 20.2892, 20.9977]])

In [183]:
torch.add(a, 10)

tensor([[10.2401, 10.5457, 10.7303],
        [10.5268, 10.6694, 10.3213],
        [10.4008, 10.2892, 10.9977]])

In [184]:
a + b

tensor([[0.9050, 1.1103, 1.6625],
        [0.9889, 1.0722, 0.4893],
        [0.5178, 0.7955, 1.6038]])

In [185]:
a - 10

tensor([[-9.7599, -9.4543, -9.2697],
        [-9.4732, -9.3306, -9.6787],
        [-9.5992, -9.7108, -9.0023]])

In [186]:
torch.sub(a, 10)

tensor([[-9.7599, -9.4543, -9.2697],
        [-9.4732, -9.3306, -9.6787],
        [-9.5992, -9.7108, -9.0023]])

In [187]:
a - b

tensor([[-0.4248, -0.0189, -0.2020],
        [ 0.0646,  0.2667,  0.1533],
        [ 0.2839, -0.2171,  0.3916]])

In [188]:
a * 10

tensor([[2.4010, 5.4572, 7.3029],
        [5.2676, 6.6945, 3.2129],
        [4.0085, 2.8919, 9.9772]])

In [189]:
torch.mul(a, 10)

tensor([[2.4010, 5.4572, 7.3029],
        [5.2676, 6.6945, 3.2129],
        [4.0085, 2.8919, 9.9772]])

In [190]:
a * b

tensor([[0.1596, 0.3081, 0.6808],
        [0.2434, 0.2696, 0.0540],
        [0.0469, 0.1464, 0.6047]])

In [191]:
a / 10

tensor([[0.0240, 0.0546, 0.0730],
        [0.0527, 0.0669, 0.0321],
        [0.0401, 0.0289, 0.0998]])

In [192]:
torch.div(a, 10)

tensor([[0.0240, 0.0546, 0.0730],
        [0.0527, 0.0669, 0.0321],
        [0.0401, 0.0289, 0.0998]])

In [193]:
a / b

tensor([[0.3611, 0.9665, 0.7834],
        [1.1398, 1.6622, 1.9124],
        [3.4264, 0.5711, 1.6461]])

In [194]:
torch.matmul(a, b)

tensor([[0.4973, 0.7251, 0.7582],
        [0.6972, 0.7297, 0.7983],
        [0.5169, 0.8480, 1.0270]])

In [195]:
a @ b

tensor([[0.4973, 0.7251, 0.7582],
        [0.6972, 0.7297, 0.7983],
        [0.5169, 0.8480, 1.0270]])

In [196]:
a ** 2

tensor([[0.0576, 0.2978, 0.5333],
        [0.2775, 0.4482, 0.1032],
        [0.1607, 0.0836, 0.9954]])

In [197]:
a ** (1 / 2)

tensor([[0.4900, 0.7387, 0.8546],
        [0.7258, 0.8182, 0.5668],
        [0.6331, 0.5378, 0.9989]])

In [198]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([1, 2, 3])

In [199]:
%%time
value = 0
for i in range(len(tensor)):
    value += a[i] + b[i]
value

CPU times: user 522 μs, sys: 487 μs, total: 1.01 ms
Wall time: 12.1 ms


tensor(2)

In [200]:
%%time
torch.matmul(a, b)

CPU times: user 996 μs, sys: 2.25 ms, total: 3.25 ms
Wall time: 8.68 ms


tensor(14)

In [201]:
%%time
a @ b

CPU times: user 271 μs, sys: 138 μs, total: 409 μs
Wall time: 475 μs


tensor(14)

In [202]:
torch.rand([3, 2]) @ torch.rand([3, 2])

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [203]:
torch.rand([3, 2]) @ torch.rand([2, 3])

tensor([[0.5035, 0.1036, 0.5227],
        [0.7028, 0.1770, 0.7280],
        [0.6863, 0.2133, 0.7090]])

In [204]:
torch.rand([2, 3]) @ torch.rand([3, 2])

tensor([[1.0542, 0.8550],
        [1.2303, 1.2689]])

In [205]:
a = torch.rand([4, 3])
a

tensor([[0.2596, 0.3507, 0.6683],
        [0.4601, 0.9545, 0.1936],
        [0.8199, 0.3752, 0.6261],
        [0.6456, 0.1400, 0.8216]])

In [206]:
b = a.T
b

tensor([[0.2596, 0.4601, 0.8199, 0.6456],
        [0.3507, 0.9545, 0.3752, 0.1400],
        [0.6683, 0.1936, 0.6261, 0.8216]])

In [207]:
a.shape, b.shape

(torch.Size([4, 3]), torch.Size([3, 4]))

In [208]:
b.T

tensor([[0.2596, 0.3507, 0.6683],
        [0.4601, 0.9545, 0.1936],
        [0.8199, 0.3752, 0.6261],
        [0.6456, 0.1400, 0.8216]])

In [209]:
torch.mm(a, a.T)

tensor([[0.6369, 0.5835, 0.7628, 0.7657],
        [0.5835, 1.1603, 0.8566, 0.5898],
        [0.7628, 0.8566, 1.2049, 1.0962],
        [0.7657, 0.5898, 1.0962, 1.1114]])

### Tensor aggregation

In [210]:
tensor = torch.arange(0, 100, 10)
tensor, tensor.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [211]:
torch.min(tensor), tensor.min()

(tensor(0), tensor(0))

In [212]:
torch.max(tensor), tensor.max()

(tensor(90), tensor(90))

In [213]:
torch.mean(tensor.type(torch.float32)), tensor.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [214]:
torch.sum(tensor), tensor.sum()

(tensor(450), tensor(450))

### Finiding positions

In [215]:
tensor

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [216]:
torch.argmax(tensor), tensor.argmax()

(tensor(9), tensor(9))

In [217]:
tensor[tensor.argmax()]

tensor(90)

In [218]:
torch.argmin(tensor), tensor.argmin()

(tensor(0), tensor(0))

In [219]:
tensor[torch.argmin(tensor)]

tensor(0)

### Reshaping, starcking, squeezing and unsqueezing tensors

In [220]:
a = torch.rand(size=[3, 5])
a

tensor([[0.6671, 0.1167, 0.3571, 0.5386, 0.2662],
        [0.1353, 0.1664, 0.5620, 0.3337, 0.3034],
        [0.6037, 0.1452, 0.8953, 0.4402, 0.7838]])

In [221]:
a.shape

torch.Size([3, 5])

In [222]:
a_reshaped = a.reshape(1, 15)
a_reshaped, a_reshaped.shape

(tensor([[0.6671, 0.1167, 0.3571, 0.5386, 0.2662, 0.1353, 0.1664, 0.5620, 0.3337,
          0.3034, 0.6037, 0.1452, 0.8953, 0.4402, 0.7838]]),
 torch.Size([1, 15]))

In [223]:
a_reshaped = a.reshape(5, 3)
a_reshaped, a_reshaped.shape

(tensor([[0.6671, 0.1167, 0.3571],
         [0.5386, 0.2662, 0.1353],
         [0.1664, 0.5620, 0.3337],
         [0.3034, 0.6037, 0.1452],
         [0.8953, 0.4402, 0.7838]]),
 torch.Size([5, 3]))

In [224]:
a_reshaped = a.reshape(15, 1)
a_reshaped, a_reshaped.shape

(tensor([[0.6671],
         [0.1167],
         [0.3571],
         [0.5386],
         [0.2662],
         [0.1353],
         [0.1664],
         [0.5620],
         [0.3337],
         [0.3034],
         [0.6037],
         [0.1452],
         [0.8953],
         [0.4402],
         [0.7838]]),
 torch.Size([15, 1]))

In [225]:
b = a.view(3, 5) # chaning b changes a - a view of a tensor shares the same memory as the original input
b, b.shape

(tensor([[0.6671, 0.1167, 0.3571, 0.5386, 0.2662],
         [0.1353, 0.1664, 0.5620, 0.3337, 0.3034],
         [0.6037, 0.1452, 0.8953, 0.4402, 0.7838]]),
 torch.Size([3, 5]))

In [226]:
b[0][0] = 19
a, b

(tensor([[19.0000,  0.1167,  0.3571,  0.5386,  0.2662],
         [ 0.1353,  0.1664,  0.5620,  0.3337,  0.3034],
         [ 0.6037,  0.1452,  0.8953,  0.4402,  0.7838]]),
 tensor([[19.0000,  0.1167,  0.3571,  0.5386,  0.2662],
         [ 0.1353,  0.1664,  0.5620,  0.3337,  0.3034],
         [ 0.6037,  0.1452,  0.8953,  0.4402,  0.7838]]))

In [227]:
a_stacked = torch.stack([a, a, a, a], dim=0)
a_stacked

tensor([[[19.0000,  0.1167,  0.3571,  0.5386,  0.2662],
         [ 0.1353,  0.1664,  0.5620,  0.3337,  0.3034],
         [ 0.6037,  0.1452,  0.8953,  0.4402,  0.7838]],

        [[19.0000,  0.1167,  0.3571,  0.5386,  0.2662],
         [ 0.1353,  0.1664,  0.5620,  0.3337,  0.3034],
         [ 0.6037,  0.1452,  0.8953,  0.4402,  0.7838]],

        [[19.0000,  0.1167,  0.3571,  0.5386,  0.2662],
         [ 0.1353,  0.1664,  0.5620,  0.3337,  0.3034],
         [ 0.6037,  0.1452,  0.8953,  0.4402,  0.7838]],

        [[19.0000,  0.1167,  0.3571,  0.5386,  0.2662],
         [ 0.1353,  0.1664,  0.5620,  0.3337,  0.3034],
         [ 0.6037,  0.1452,  0.8953,  0.4402,  0.7838]]])

In [228]:
a_stacked = torch.stack([a, a, a, a], dim=1)
a_stacked

tensor([[[19.0000,  0.1167,  0.3571,  0.5386,  0.2662],
         [19.0000,  0.1167,  0.3571,  0.5386,  0.2662],
         [19.0000,  0.1167,  0.3571,  0.5386,  0.2662],
         [19.0000,  0.1167,  0.3571,  0.5386,  0.2662]],

        [[ 0.1353,  0.1664,  0.5620,  0.3337,  0.3034],
         [ 0.1353,  0.1664,  0.5620,  0.3337,  0.3034],
         [ 0.1353,  0.1664,  0.5620,  0.3337,  0.3034],
         [ 0.1353,  0.1664,  0.5620,  0.3337,  0.3034]],

        [[ 0.6037,  0.1452,  0.8953,  0.4402,  0.7838],
         [ 0.6037,  0.1452,  0.8953,  0.4402,  0.7838],
         [ 0.6037,  0.1452,  0.8953,  0.4402,  0.7838],
         [ 0.6037,  0.1452,  0.8953,  0.4402,  0.7838]]])

In [229]:
b = torch.rand(size=[1, 1, 3])
b, b.shape

(tensor([[[0.2089, 0.1943, 0.7621]]]), torch.Size([1, 1, 3]))

In [230]:
c = b.squeeze()
c, c.shape

(tensor([0.2089, 0.1943, 0.7621]), torch.Size([3]))

In [231]:
d = c.unsqueeze(dim=0).unsqueeze(dim=0)
d, d.shape

(tensor([[[0.2089, 0.1943, 0.7621]]]), torch.Size([1, 1, 3]))

In [232]:
e = c.unsqueeze(dim=-2)
e, e.shape

(tensor([[0.2089, 0.1943, 0.7621]]), torch.Size([1, 3]))

In [233]:
f = c.unsqueeze(dim=1)
f, f.shape

(tensor([[0.2089],
         [0.1943],
         [0.7621]]),
 torch.Size([3, 1]))

In [234]:
y = torch.rand(size=(224, 224, 3))
y, y.shape

(tensor([[[0.4492, 0.9147, 0.4331],
          [0.7791, 0.1290, 0.4005],
          [0.3250, 0.1490, 0.6707],
          ...,
          [0.3089, 0.8246, 0.4408],
          [0.2840, 0.5214, 0.9279],
          [0.3996, 0.5807, 0.5808]],
 
         [[0.1393, 0.7707, 0.7882],
          [0.4899, 0.9927, 0.4824],
          [0.1632, 0.4668, 0.1680],
          ...,
          [0.5965, 0.2040, 0.5427],
          [0.3470, 0.3069, 0.0041],
          [0.4528, 0.7516, 0.8017]],
 
         [[0.9955, 0.2985, 0.6563],
          [0.7581, 0.6282, 0.8758],
          [0.3359, 0.4271, 0.3561],
          ...,
          [0.0862, 0.9920, 0.8231],
          [0.8410, 0.5124, 0.8447],
          [0.1334, 0.9151, 0.0348]],
 
         ...,
 
         [[0.2788, 0.2512, 0.4265],
          [0.1872, 0.6222, 0.5388],
          [0.3306, 0.6649, 0.2649],
          ...,
          [0.9834, 0.2132, 0.0659],
          [0.6738, 0.3455, 0.1766],
          [0.1755, 0.4081, 0.2396]],
 
         [[0.5785, 0.3757, 0.0989],
          [0

In [235]:
z = y.permute((2, 0, 1))
z, z.shape

(tensor([[[0.4492, 0.7791, 0.3250,  ..., 0.3089, 0.2840, 0.3996],
          [0.1393, 0.4899, 0.1632,  ..., 0.5965, 0.3470, 0.4528],
          [0.9955, 0.7581, 0.3359,  ..., 0.0862, 0.8410, 0.1334],
          ...,
          [0.2788, 0.1872, 0.3306,  ..., 0.9834, 0.6738, 0.1755],
          [0.5785, 0.6180, 0.1568,  ..., 0.2600, 0.6625, 0.2132],
          [0.1401, 0.0325, 0.4473,  ..., 0.2455, 0.0832, 0.3273]],
 
         [[0.9147, 0.1290, 0.1490,  ..., 0.8246, 0.5214, 0.5807],
          [0.7707, 0.9927, 0.4668,  ..., 0.2040, 0.3069, 0.7516],
          [0.2985, 0.6282, 0.4271,  ..., 0.9920, 0.5124, 0.9151],
          ...,
          [0.2512, 0.6222, 0.6649,  ..., 0.2132, 0.3455, 0.4081],
          [0.3757, 0.5219, 0.4104,  ..., 0.1633, 0.1261, 0.2675],
          [0.7458, 0.0745, 0.4460,  ..., 0.1387, 0.7169, 0.7462]],
 
         [[0.4331, 0.4005, 0.6707,  ..., 0.4408, 0.9279, 0.5808],
          [0.7882, 0.4824, 0.1680,  ..., 0.5427, 0.0041, 0.8017],
          [0.6563, 0.8758, 0.3561,  ...,

### Indexing

In [236]:
x = torch.arange(1, 10, 1)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [237]:
y = x.reshape(1, 3, 3)
y

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [238]:
y[0, 0, 0], y[0, 0, 1], y[0, 0, 2]

(tensor(1), tensor(2), tensor(3))

In [239]:
y[0, 1]

tensor([4, 5, 6])

In [240]:
y[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [241]:
y[0, 1, :2]

tensor([4, 5])

In [242]:
y[0, 1, 1:]

tensor([5, 6])

In [243]:
y[0][0]

tensor([1, 2, 3])

In [244]:
y[0][1][1:]

tensor([5, 6])

In [245]:
y[0][0][0] = 10

In [246]:
y, x

(tensor([[[10,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]]]),
 tensor([10,  2,  3,  4,  5,  6,  7,  8,  9]))

In [247]:
y[:, :, 1]

tensor([[2, 5, 8]])

In [248]:
y[:, :, 0]

tensor([[10,  4,  7]])

In [249]:
y[0][0], y[0, 0, :]

(tensor([10,  2,  3]), tensor([10,  2,  3]))

In [250]:
y[0][2][-1]

tensor(9)

In [251]:
y[:, :, 2]

tensor([[3, 6, 9]])

## PyTorch and NumPy

In [252]:
array = np.arange(1, 10)
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [253]:
tensor = torch.from_numpy(array)
tensor

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [254]:
array = array + 1
array, tensor

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10]),
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [255]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [256]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility

In [257]:
random_a = torch.rand(3, 3)
random_b = torch.rand(3, 3)

In [258]:
random_a, random_b

(tensor([[0.8974, 0.2768, 0.6498],
         [0.0583, 0.2528, 0.8281],
         [0.0411, 0.1029, 0.0332]]),
 tensor([[0.7918, 0.4645, 0.1734],
         [0.8508, 0.0282, 0.6474],
         [0.3719, 0.1917, 0.5551]]))

In [259]:
random_a == random_b

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [260]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_c = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_d = torch.rand(3, 4)

random_c, random_d

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]))

In [261]:
random_c == random_d

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

## Running tensors and PyTorch objects on the GPUs

### Getting a GPU

In [262]:
!nvidia-smi

zsh:1: command not found: nvidia-smi


### Check for GPU access with PyTorch

In [263]:
import torch
torch.cuda.is_available()

False

In [264]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [265]:
torch.cuda.device_count()

0

### Puting tensors on the GPU

In [266]:
tensor = torch.tensor([1, 2, 3], device="cpu")
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [267]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu, tensor_on_gpu.device

(tensor([1, 2, 3]), device(type='cpu'))

### Moving tensors back to the CPU

In [268]:
tensor = torch.tensor([1, 2, 3], device=device)
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [269]:
tensor_on_cpu = tensor.to("cpu")
tensor_on_cpu, tensor_on_cpu.device

(tensor([1, 2, 3]), device(type='cpu'))

In [270]:
array = tensor.cpu().numpy()
array

array([1, 2, 3])

## Exercises and extra-curriculum