# 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.7.1


## Introduction to Tensors

Link: https://docs.pytorch.org/docs/stable/tensors.html

### Creating tensors

PyTorch tensors are created using torch.Tensor() = https://pytorch.org/docs/stable/tensors.html

In [3]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as Python int
scalar.item()

7

In [6]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [ ]:
# Matrix
matrix = torch.tensor([[7, 8],
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
matrix.ndim

2

In [11]:
matrix.shape

torch.Size([2, 2])

In [12]:
matrix[0]

tensor([7, 8])

In [13]:
matrix[1]

tensor([ 9, 10])

In [14]:
# Tensor
tensor = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [15]:
tensor.ndim

3

In [16]:
tensor.shape

torch.Size([1, 3, 3])

In [17]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [18]:
tensor[0][1]

tensor([4, 5, 6])

In [19]:
tensor[0][1][2]

tensor(6)

### Random tensors

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers

Torch random tensors - https://pytorch.org/docs/stable/generated/torch.rand.html

In [20]:
# Create a random tensor of size / shape (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2105, 0.6644, 0.2312, 0.5239],
        [0.8002, 0.9629, 0.7550, 0.2121],
        [0.6954, 0.2267, 0.1422, 0.2061]])

In [21]:
random_tensor.ndim

2

In [22]:
random_tensor = torch.rand(3, 3, 3)
random_tensor

tensor([[[0.4745, 0.3935, 0.4855],
         [0.9720, 0.9430, 0.7347],
         [0.4860, 0.1493, 0.8200]],

        [[0.1396, 0.1112, 0.8863],
         [0.6445, 0.7300, 0.2712],
         [0.3801, 0.2679, 0.7729]],

        [[0.0839, 0.1112, 0.7340],
         [0.6669, 0.0267, 0.9945],
         [0.8615, 0.6843, 0.4656]]])

In [23]:
torch.rand(size=(1, 2, 3))

tensor([[[0.9869, 0.1881, 0.9063],
         [0.5757, 0.1852, 0.6344]]])

In [24]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, width, colour channels (R, G, B
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [25]:
# Create a random tensor of size / shape (3, 4)
random_tensor = torch.rand(3, 4)

In [26]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
# Create a tensor of all ones
ones = torch.ones(size=(3, 4))

In [29]:
ones.dtype

torch.float32

In [30]:
ones * random_tensor

tensor([[0.5207, 0.3133, 0.1329, 0.4848],
        [0.1975, 0.4487, 0.0189, 0.3238],
        [0.5146, 0.5702, 0.6372, 0.5092]])

### Creating a range of tensors and tensors-like

In [31]:
# Use torch.range() and get deprecated message, use torch.arange()
torch.range(2, 8)

/var/folders/hz/kv51gkp17hd22cn05cv5whww0000gn/T/ipykernel_23486/2340538228.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(2, 8)


tensor([2., 3., 4., 5., 6., 7., 8.])

In [32]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
one_to_ten = torch.arange(1, 11)

In [34]:
torch.arange(start=0, end=1000, step=99)

tensor([  0,  99, 198, 297, 396, 495, 594, 693, 792, 891, 990])

In [35]:
# Creating tensors like
ten_zeres = torch.zeros_like(input=one_to_ten)
ten_zeres

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note**: Tensor datatypes is one of the 3 big errors you'll run into with PyTorch & deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing - https://en.wikipedia.org/wiki/Precision_(computer_science)#:~:text=In%20computer%20science%2C%20the%20precision,used%20to%20express%20a%20value.

In [36]:
# Float 32 tensor
float_32_tensor = torch.tensor(
    [3.0, 6.0, 9.0],
    dtype=None, # what datatype is the tensor (e.g. float32 or float16)
    device=None, # What device is your tensor on
    requires_grad=False # whether or not to track gradients with this tensors operations
)

float_32_tensor

tensor([3., 6., 9.])

In [37]:
float_16_tensor = torch.tensor(
    [3.0 , 6.0, 9.0],
    dtype=torch.float16,
    device="mps",
    requires_grad=False
)

float_16_tensor.dtype

torch.float16

In [38]:
float_64_tensor = float_32_tensor.type(torch.float64)
float_64_tensor

tensor([3., 6., 9.], dtype=torch.float64)

In [39]:
float_16_tensor.shape, float_16_tensor.device, float_16_tensor.dtype

(torch.Size([3]), device(type='mps', index=0), torch.float16)

In [40]:
float_64_tensor * float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float64)

In [41]:
float_32_tensor * float_64_tensor

tensor([ 9., 36., 81.], dtype=torch.float64)

In [42]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [43]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to do get datatype from a tensor, can use tensor.dtype
2. Tensors not right shape - to get shape from a tensor, can use tensor.shape
3. Tensors not on the right device - to get device from a tensor, can use tensor.device

In [44]:
# Create a tensor
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.2128, 0.3069, 0.2069, 0.1393],
        [0.5390, 0.0108, 0.4026, 0.7381],
        [0.7512, 0.2466, 0.2654, 0.5745]])

In [45]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.2128, 0.3069, 0.2069, 0.1393],
        [0.5390, 0.0108, 0.4026, 0.7381],
        [0.7512, 0.2466, 0.2654, 0.5745]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating tensors

Tensor opertions include:

- Addition
- Subtraction
- Multiplication (element-wise)
- Division
- Matrix multiplication

In [46]:
a = torch.rand(size=(3, 3))
b = torch.rand(size=(3, 3))

In [47]:
a

tensor([[0.8819, 0.0372, 0.8463],
        [0.8925, 0.7164, 0.4614],
        [0.2305, 0.9800, 0.8495]])

In [48]:
b

tensor([[0.4872, 0.0709, 0.6761],
        [0.7933, 0.8996, 0.7780],
        [0.6484, 0.6954, 0.5058]])

In [49]:
# Add 10 to tensor
a + 20, torch.add(a, 10)

(tensor([[20.8819, 20.0372, 20.8463],
         [20.8925, 20.7164, 20.4614],
         [20.2305, 20.9800, 20.8495]]),
 tensor([[10.8819, 10.0372, 10.8463],
         [10.8925, 10.7164, 10.4614],
         [10.2305, 10.9800, 10.8495]]))

In [50]:
a + b

tensor([[1.3691, 0.1081, 1.5224],
        [1.6858, 1.6160, 1.2394],
        [0.8789, 1.6754, 1.3552]])

In [51]:
# Subtract 10 to tensor
a - 10, torch.sub(a, 10)

(tensor([[-9.1181, -9.9628, -9.1537],
         [-9.1075, -9.2836, -9.5386],
         [-9.7695, -9.0200, -9.1505]]),
 tensor([[-9.1181, -9.9628, -9.1537],
         [-9.1075, -9.2836, -9.5386],
         [-9.7695, -9.0200, -9.1505]]))

In [52]:
a - b

tensor([[ 0.3947, -0.0336,  0.1702],
        [ 0.0992, -0.1832, -0.3165],
        [-0.4180,  0.2845,  0.3437]])

In [53]:
# Multiply tensor by 10
a * 10, torch.mul(a, 10)

(tensor([[8.8194, 0.3724, 8.4628],
         [8.9252, 7.1636, 4.6144],
         [2.3046, 9.7999, 8.4946]]),
 tensor([[8.8194, 0.3724, 8.4628],
         [8.9252, 7.1636, 4.6144],
         [2.3046, 9.7999, 8.4946]]))

In [54]:
a * b

tensor([[0.4297, 0.0026, 0.5722],
        [0.7080, 0.6444, 0.3590],
        [0.1494, 0.6815, 0.4296]])

In [55]:
# Divide tensor by 10
a / 10, torch.div(a, 10)

(tensor([[0.0882, 0.0037, 0.0846],
         [0.0893, 0.0716, 0.0461],
         [0.0230, 0.0980, 0.0849]]),
 tensor([[0.0882, 0.0037, 0.0846],
         [0.0893, 0.0716, 0.0461],
         [0.0230, 0.0980, 0.0849]]))

In [56]:
a / b

tensor([[1.8102, 0.5254, 1.2517],
        [1.1251, 0.7963, 0.5931],
        [0.3554, 1.4092, 1.6795]])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix mutliplication (dot product)

More information on multiplying matrices - https://www.mathsisfun.com/algebra/matrix-multiplying.html

There are two main rules that performing matrix mutliplication needs to satisfy:

1. The **inner dimensions** must match:

- (3, 2) @ (3, 2) won't work
- (2, 3) @ (3, 2) will work
- (3, 2) @ (2, 3) will work

2. The resulting matrix has the shape of the **outer dimensions**:
- (2, 3) @ (3, 2) -> (2, 2)
- (3, 2) @ (2, 3) -> (3, 3)

In [57]:
# Multiply tensor by tensor
torch.matmul(a, b), a @ b

(tensor([[1.0080, 0.6846, 1.0533],
         [1.3023, 1.0286, 1.3941],
         [1.4405, 1.4887, 1.3478]]),
 tensor([[1.0080, 0.6846, 1.0533],
         [1.3023, 1.0286, 1.3941],
         [1.4405, 1.4887, 1.3478]]))

In [58]:
# Raise tensor to the power of 2
a ** 2

tensor([[0.7778, 0.0014, 0.7162],
        [0.7966, 0.5132, 0.2129],
        [0.0531, 0.9604, 0.7216]])

In [59]:
# Raise tensor to the power of 1 / 2
a ** (1 / 2)

tensor([[0.9391, 0.1930, 0.9199],
        [0.9447, 0.8464, 0.6793],
        [0.4801, 0.9899, 0.9217]])

In [60]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([1, 2, 3])

In [61]:
%%time
value = 0
for i in range(len(tensor)):
    value += a[i] + b[i]
value

CPU times: user 315 μs, sys: 171 μs, total: 486 μs
Wall time: 334 μs


tensor(2)

In [62]:
%%time
torch.matmul(a, b)

CPU times: user 536 μs, sys: 644 μs, total: 1.18 ms
Wall time: 717 μs


tensor(14)

In [63]:
%%time
a @ b

CPU times: user 180 μs, sys: 57 μs, total: 237 μs
Wall time: 235 μs


tensor(14)

One of the most common errors in deep learning: shape errors

In [64]:
torch.rand([3, 2]) @ torch.rand([3, 2])

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes or dimensions of a given tensor.

In [65]:
torch.rand([3, 2]) @ torch.rand([2, 3])

tensor([[0.7308, 0.2095, 0.6549],
        [0.3451, 0.0858, 0.5605],
        [0.4752, 0.1304, 0.5361]])

In [66]:
torch.rand([2, 3]) @ torch.rand([3, 2])

tensor([[0.4945, 0.5409],
        [0.3827, 0.7132]])

In [67]:
a = torch.rand([4, 3])
a

tensor([[0.8532, 0.8794, 0.9250],
        [0.9727, 0.6706, 0.5596],
        [0.4046, 0.8069, 0.0235],
        [0.7902, 0.2215, 0.3293]])

In [68]:
b = a.T
b

tensor([[0.8532, 0.9727, 0.4046, 0.7902],
        [0.8794, 0.6706, 0.8069, 0.2215],
        [0.9250, 0.5596, 0.0235, 0.3293]])

In [69]:
a.shape, b.shape

(torch.Size([4, 3]), torch.Size([3, 4]))

In [70]:
b.T

tensor([[0.8532, 0.8794, 0.9250],
        [0.9727, 0.6706, 0.5596],
        [0.4046, 0.8069, 0.0235],
        [0.7902, 0.2215, 0.3293]])

In [71]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape} (same shape as above), tensor_B.T = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(a, b.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

NameError: name 'tensor_A' is not defined

In [72]:
torch.mm(a, a.T)

tensor([[2.3570, 1.9373, 1.0766, 1.1736],
        [1.9373, 1.7090, 0.9478, 1.1014],
        [1.0766, 0.9478, 0.8153, 0.5062],
        [1.1736, 1.1014, 0.5062, 0.7819]])

### Finding the min, max, mean, sum, etc (tensor aggregation)

In [73]:
# Create a tensor
tensor = torch.arange(0, 100, 10)
tensor, tensor.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [74]:
# Find the min
torch.min(tensor), tensor.min()

(tensor(0), tensor(0))

In [75]:
# Find the max
torch.max(tensor), tensor.max()

(tensor(90), tensor(90))

In [76]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(tensor.type(torch.float32)), tensor.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [77]:
# Find the sum
torch.sum(tensor), tensor.sum()

(tensor(450), tensor(450))

### Finding the positional min and max

In [78]:
tensor

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [79]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of targt tensor where the minimum value occurs 
torch.argmax(tensor), tensor.argmax()

(tensor(9), tensor(9))

In [80]:
# Find the position in tensor that has the maximum value with argmax()
tensor[tensor.argmax()]

tensor(90)

In [81]:
torch.argmin(tensor), tensor.argmin()

(tensor(0), tensor(0))

In [82]:
tensor[torch.argmin(tensor)]

tensor(0)

### Reshaping, stacking, squeezing and unsqueezing tensors

- Reshaping - reshapes an input tensor to a defined shape
- View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
- Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
- Squeeze - removes all `1` dimensions from a tensor
- Unsqueeze - add a `1` dimension to a target tensor
- Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [83]:
# Let's create a tensor
a = torch.rand(size=[3, 5])
a

tensor([[0.4868, 0.6040, 0.5651, 0.1861, 0.6963],
        [0.5483, 0.6567, 0.0601, 0.7948, 0.7239],
        [0.4406, 0.1099, 0.5892, 0.4038, 0.6269]])

In [84]:
a.shape

torch.Size([3, 5])

In [85]:
# Add an extra dimension
a_reshaped = a.reshape(1, 15)
a_reshaped, a_reshaped.shape

(tensor([[0.4868, 0.6040, 0.5651, 0.1861, 0.6963, 0.5483, 0.6567, 0.0601, 0.7948,
          0.7239, 0.4406, 0.1099, 0.5892, 0.4038, 0.6269]]),
 torch.Size([1, 15]))

In [86]:
a_reshaped = a.reshape(5, 3)
a_reshaped, a_reshaped.shape

(tensor([[0.4868, 0.6040, 0.5651],
         [0.1861, 0.6963, 0.5483],
         [0.6567, 0.0601, 0.7948],
         [0.7239, 0.4406, 0.1099],
         [0.5892, 0.4038, 0.6269]]),
 torch.Size([5, 3]))

In [87]:
a_reshaped = a.reshape(15, 1)
a_reshaped, a_reshaped.shape

(tensor([[0.4868],
         [0.6040],
         [0.5651],
         [0.1861],
         [0.6963],
         [0.5483],
         [0.6567],
         [0.0601],
         [0.7948],
         [0.7239],
         [0.4406],
         [0.1099],
         [0.5892],
         [0.4038],
         [0.6269]]),
 torch.Size([15, 1]))

In [88]:
# Change the view 
b = a.view(3, 5) # chaning b changes a - a view of a tensor shares the same memory as the original input
b, b.shape

(tensor([[0.4868, 0.6040, 0.5651, 0.1861, 0.6963],
         [0.5483, 0.6567, 0.0601, 0.7948, 0.7239],
         [0.4406, 0.1099, 0.5892, 0.4038, 0.6269]]),
 torch.Size([3, 5]))

In [89]:
b[0][0] = 19
a, b

(tensor([[19.0000,  0.6040,  0.5651,  0.1861,  0.6963],
         [ 0.5483,  0.6567,  0.0601,  0.7948,  0.7239],
         [ 0.4406,  0.1099,  0.5892,  0.4038,  0.6269]]),
 tensor([[19.0000,  0.6040,  0.5651,  0.1861,  0.6963],
         [ 0.5483,  0.6567,  0.0601,  0.7948,  0.7239],
         [ 0.4406,  0.1099,  0.5892,  0.4038,  0.6269]]))

In [90]:
a_stacked = torch.stack([a, a, a, a], dim=0)
a_stacked

tensor([[[19.0000,  0.6040,  0.5651,  0.1861,  0.6963],
         [ 0.5483,  0.6567,  0.0601,  0.7948,  0.7239],
         [ 0.4406,  0.1099,  0.5892,  0.4038,  0.6269]],

        [[19.0000,  0.6040,  0.5651,  0.1861,  0.6963],
         [ 0.5483,  0.6567,  0.0601,  0.7948,  0.7239],
         [ 0.4406,  0.1099,  0.5892,  0.4038,  0.6269]],

        [[19.0000,  0.6040,  0.5651,  0.1861,  0.6963],
         [ 0.5483,  0.6567,  0.0601,  0.7948,  0.7239],
         [ 0.4406,  0.1099,  0.5892,  0.4038,  0.6269]],

        [[19.0000,  0.6040,  0.5651,  0.1861,  0.6963],
         [ 0.5483,  0.6567,  0.0601,  0.7948,  0.7239],
         [ 0.4406,  0.1099,  0.5892,  0.4038,  0.6269]]])

In [91]:
a_stacked = torch.stack([a, a, a, a], dim=1)
a_stacked

tensor([[[19.0000,  0.6040,  0.5651,  0.1861,  0.6963],
         [19.0000,  0.6040,  0.5651,  0.1861,  0.6963],
         [19.0000,  0.6040,  0.5651,  0.1861,  0.6963],
         [19.0000,  0.6040,  0.5651,  0.1861,  0.6963]],

        [[ 0.5483,  0.6567,  0.0601,  0.7948,  0.7239],
         [ 0.5483,  0.6567,  0.0601,  0.7948,  0.7239],
         [ 0.5483,  0.6567,  0.0601,  0.7948,  0.7239],
         [ 0.5483,  0.6567,  0.0601,  0.7948,  0.7239]],

        [[ 0.4406,  0.1099,  0.5892,  0.4038,  0.6269],
         [ 0.4406,  0.1099,  0.5892,  0.4038,  0.6269],
         [ 0.4406,  0.1099,  0.5892,  0.4038,  0.6269],
         [ 0.4406,  0.1099,  0.5892,  0.4038,  0.6269]]])

In [92]:
b = torch.rand(size=[1, 1, 3])
b, b.shape

(tensor([[[0.5826, 0.5229, 0.3885]]]), torch.Size([1, 1, 3]))

In [93]:
# torch.squeeze() - removes all single dimensions from a target tensor
c = b.squeeze()
c, c.shape

(tensor([0.5826, 0.5229, 0.3885]), torch.Size([3]))

In [94]:
# Remove extra dimensions from x_reshaped
d = c.unsqueeze(dim=0).unsqueeze(dim=0)
d, d.shape

(tensor([[[0.5826, 0.5229, 0.3885]]]), torch.Size([1, 1, 3]))

In [95]:
e = c.unsqueeze(dim=-2)
e, e.shape

(tensor([[0.5826, 0.5229, 0.3885]]), torch.Size([1, 3]))

In [96]:
f = c.unsqueeze(dim=1)
f, f.shape

(tensor([[0.5826],
         [0.5229],
         [0.3885]]),
 torch.Size([3, 1]))

In [97]:
y = torch.rand(size=(224, 224, 3))
y, y.shape

(tensor([[[0.9390, 0.9157, 0.4817],
          [0.0299, 0.6037, 0.6709],
          [0.2481, 0.1196, 0.3228],
          ...,
          [0.6905, 0.8884, 0.6654],
          [0.9930, 0.5028, 0.2070],
          [0.9925, 0.0194, 0.9053]],
 
         [[0.7268, 0.9876, 0.5597],
          [0.9536, 0.7782, 0.6395],
          [0.8140, 0.0580, 0.2135],
          ...,
          [0.0202, 0.8696, 0.0900],
          [0.7159, 0.7364, 0.9489],
          [0.4390, 0.9876, 0.7486]],
 
         [[0.0804, 0.0737, 0.9941],
          [0.4258, 0.7591, 0.5282],
          [0.3839, 0.2166, 0.3339],
          ...,
          [0.0849, 0.2557, 0.9505],
          [0.6723, 0.8729, 0.7789],
          [0.4705, 0.1215, 0.3287]],
 
         ...,
 
         [[0.2349, 0.3573, 0.1680],
          [0.4723, 0.6784, 0.5339],
          [0.7690, 0.6808, 0.9523],
          ...,
          [0.3788, 0.0847, 0.3696],
          [0.8557, 0.9763, 0.2997],
          [0.0902, 0.2867, 0.7327]],
 
         [[0.9249, 0.9200, 0.9047],
          [0

In [98]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
# Permute the original tensor to rearrange the axis (or dim) order
z = y.permute((2, 0, 1)) # shifts axis 0->1, 1->2, 2->0

z, z.shape

(tensor([[[0.9390, 0.0299, 0.2481,  ..., 0.6905, 0.9930, 0.9925],
          [0.7268, 0.9536, 0.8140,  ..., 0.0202, 0.7159, 0.4390],
          [0.0804, 0.4258, 0.3839,  ..., 0.0849, 0.6723, 0.4705],
          ...,
          [0.2349, 0.4723, 0.7690,  ..., 0.3788, 0.8557, 0.0902],
          [0.9249, 0.0632, 0.3376,  ..., 0.5258, 0.5352, 0.4444],
          [0.7653, 0.6369, 0.8002,  ..., 0.3127, 0.8467, 0.7182]],
 
         [[0.9157, 0.6037, 0.1196,  ..., 0.8884, 0.5028, 0.0194],
          [0.9876, 0.7782, 0.0580,  ..., 0.8696, 0.7364, 0.9876],
          [0.0737, 0.7591, 0.2166,  ..., 0.2557, 0.8729, 0.1215],
          ...,
          [0.3573, 0.6784, 0.6808,  ..., 0.0847, 0.9763, 0.2867],
          [0.9200, 0.1346, 0.8031,  ..., 0.9006, 0.4155, 0.4532],
          [0.2055, 0.8274, 0.9880,  ..., 0.1695, 0.8548, 0.6445]],
 
         [[0.4817, 0.6709, 0.3228,  ..., 0.6654, 0.2070, 0.9053],
          [0.5597, 0.6395, 0.2135,  ..., 0.0900, 0.9489, 0.7486],
          [0.9941, 0.5282, 0.3339,  ...,

### Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy.

In [99]:
# Create a tensor
x = torch.arange(1, 10, 1)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
y = x.reshape(1, 3, 3)
y

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [101]:
# Let's index on our new tensor
y[0, 0, 0], y[0, 0, 1], y[0, 0, 2]

(tensor(1), tensor(2), tensor(3))

In [102]:
# Let's index on the middle bracket (dim=1)
y[0, 0]

tensor([1, 2, 3])

In [103]:
# Let's index on the most inner bracket (last dimension)
x[0][1][1]

IndexError: index 1 is out of bounds for dimension 0 with size 0

In [104]:
y[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [105]:
# You can also use ":" to select "all" of a target dimension
y[0, 1, :2]

tensor([4, 5])

In [106]:
y[0, 1, 1:]

tensor([5, 6])

In [107]:
y[0][0]

tensor([1, 2, 3])

In [108]:
y[0][1][1:]

tensor([5, 6])

In [109]:
y[0][0][0] = 10

In [110]:
y, x

(tensor([[[10,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]]]),
 tensor([10,  2,  3,  4,  5,  6,  7,  8,  9]))

In [111]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
y[:, :, 1]

tensor([[2, 5, 8]])

In [112]:
y[:, :, 0]

tensor([[10,  4,  7]])

In [113]:
y[0][0], y[0, 0, :]

(tensor([10,  2,  3]), tensor([10,  2,  3]))

In [114]:
# Index on x to return 9
y[0][2][-1]

tensor(9)

In [115]:
# Index on x to return 3, 6, 9
y[:, :, 2]

tensor([[3, 6, 9]])

## PyTorch tensors & NumPy
NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

- Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
- PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [116]:
array = np.arange(1, 10)
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
# NumPy array to tensor
tensor = torch.from_numpy(array)
tensor

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
# Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10]),
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [119]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [120]:
# Change the tesnor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducbility (trying to take random out of random)

In short how a neural network learns:

start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [121]:
# Create two random tensors
random_a = torch.rand(3, 3)
random_b = torch.rand(3, 3)

In [122]:
random_a, random_b

(tensor([[0.0921, 0.6660, 0.4362],
         [0.1558, 0.1642, 0.0852],
         [0.8322, 0.1101, 0.2027]]),
 tensor([[0.3418, 0.1094, 0.4366],
         [0.8908, 0.2524, 0.7794],
         [0.5150, 0.6854, 0.5510]]))

In [123]:
random_a == random_b

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [124]:
# Let's make some random but reproducible tensors
# Set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_c = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_d = torch.rand(3, 4)

random_c, random_d

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]))

In [125]:
random_c == random_d

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

Extra resources for reproducibility:

- https://pytorch.org/docs/stable/notes/randomness.html
- https://en.wikipedia.org/wiki/Random_seed

## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good).

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options..., see this post for what option to get: https://timdettmers.com/2020/09/07/which-gpu-for-deep-learning/
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation: https://pytorch.org/get-started/locally/

In [126]:
!nvidia-smi

zsh:1: command not found: nvidia-smi


### 2. Check for GPU access with PyTorch

In [127]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

False

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code: https://pytorch.org/docs/stable/notes/cuda.html#best-practices

In [128]:
# Setup device agnostic code 
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [129]:
# Count number of devices
torch.cuda.device_count()

0

### 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [130]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3], device="cpu")

# Tensor not on GPU
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [131]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu, tensor_on_gpu.device

(tensor([1, 2, 3]), device(type='cpu'))

### 4. Moving tensors back to the CPU

In [132]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

array([1, 2, 3])

In [133]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [134]:
tensor = torch.tensor([1, 2, 3], device=device)
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [135]:
tensor_on_cpu = tensor.to("cpu")
tensor_on_cpu, tensor_on_cpu.device

(tensor([1, 2, 3]), device(type='cpu'))

In [136]:
array = tensor.cpu().numpy()
array

array([1, 2, 3])

## Exercises and extra-curriculum

See exercises for this notebook here: https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises See the template exercises notebook for this module here: https://github.com/mrdbourke/pytorch-deep-learning/blob/main/extras/exercises/00_pytorch_fundamentals_exercises.ipynb