## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.7.1


## Introduction to Tensors

### Creating tensors

Link: https://docs.pytorch.org/docs/stable/tensors.html

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [ ]:
# matrix
matrix = torch.tensor([[7, 8], 
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
matrix.ndim

2

In [12]:
matrix.shape

torch.Size([2, 2])

In [13]:
matrix[0]

tensor([7, 8])

In [14]:
matrix[1]

tensor([ 9, 10])

In [15]:
# tensor
tensor = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [16]:
tensor.ndim

3

In [17]:
tensor.shape

torch.Size([1, 3, 3])

In [18]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [20]:
tensor[0][1]

tensor([4, 5, 6])

In [21]:
tensor[0][1][2]

tensor(6)

In [ ]:
# 1:35:05