## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.7.1


## Introduction to Tensors

Link: https://docs.pytorch.org/docs/stable/tensors.html

### Creating tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# matrix
matrix = torch.tensor([[7, 8], 
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
matrix.ndim

2

In [10]:
matrix.shape

torch.Size([2, 2])

In [11]:
matrix[0]

tensor([7, 8])

In [12]:
matrix[1]

tensor([ 9, 10])

In [13]:
# tensor
tensor = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
tensor.ndim

3

In [15]:
tensor.shape

torch.Size([1, 3, 3])

In [16]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [17]:
tensor[0][1]

tensor([4, 5, 6])

In [18]:
tensor[0][1][2]

tensor(6)

### Random tensors

In [19]:
# Create a random tensor of size / shape (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6600, 0.3630, 0.4246, 0.3353],
        [0.7734, 0.8054, 0.4783, 0.8588],
        [0.8588, 0.8325, 0.9544, 0.7341]])

In [20]:
random_tensor.ndim

2

In [21]:
random_tensor = torch.rand(3, 3, 3)
random_tensor

tensor([[[0.6559, 0.8455, 0.4565],
         [0.7860, 0.3010, 0.3781],
         [0.2872, 0.8197, 0.0738]],

        [[0.9075, 0.5706, 0.4562],
         [0.1998, 0.0831, 0.3648],
         [0.0394, 0.5895, 0.6627]],

        [[0.7817, 0.8049, 0.2082],
         [0.6576, 0.5872, 0.5963],
         [0.9689, 0.1450, 0.7034]]])

In [22]:
torch.rand(size=(1, 2, 3))

tensor([[[0.3796, 0.9756, 0.2624],
         [0.4727, 0.8908, 0.7700]]])

In [23]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [24]:
random_tensor = torch.rand(size=(3, 4))
random_tensor

tensor([[0.7107, 0.7929, 0.0545, 0.2425],
        [0.3116, 0.7630, 0.7956, 0.7726],
        [0.3124, 0.1015, 0.3025, 0.3299]])

In [25]:
# tensor of zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
# tensor of ones
ones = torch.ones(size=(3, 4))

In [28]:
ones.dtype

torch.float32

In [29]:
ones * random_tensor

tensor([[0.7107, 0.7929, 0.0545, 0.2425],
        [0.3116, 0.7630, 0.7956, 0.7726],
        [0.3124, 0.1015, 0.3025, 0.3299]])

### Creating a range of tensors and tensors-like

In [30]:
torch.range(2, 8)

/var/folders/zd/7ryz379j2dz9shhk8m8k4zx40000gn/T/ipykernel_3183/616276269.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(2, 8)


tensor([2., 3., 4., 5., 6., 7., 8.])

In [31]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
one_to_ten = torch.arange(1, 11)

In [33]:
torch.arange(start=0, end=1000, step=99)

tensor([  0,  99, 198, 297, 396, 495, 594, 693, 792, 891, 990])

In [34]:
ten_zeres = torch.zeros_like(input=one_to_ten)
ten_zeres

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [35]:
float_32_tensor = torch.tensor([3.0 , 6.0, 9.0], 
                               dtype=torch.float32)
float_32_tensor.dtype

torch.float32

In [36]:
float_16_tensor = torch.tensor([3.0 , 6.0, 9.0], 
                               dtype=torch.float16, # datatype of tensor
                               device="mps",
                               requires_grad=False)
float_16_tensor.dtype

torch.float16

In [37]:
float_64_tensor = float_32_tensor.type(torch.float64)
float_64_tensor

tensor([3., 6., 9.], dtype=torch.float64)

In [38]:
float_16_tensor.shape, float_16_tensor.device, float_16_tensor.dtype

(torch.Size([3]), device(type='mps', index=0), torch.float16)

In [39]:
float_64_tensor * float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float64)

In [40]:
float_32_tensor * float_64_tensor

tensor([ 9., 36., 81.], dtype=torch.float64)

In [41]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [42]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Manipulating tensors

In [43]:
a = torch.rand(size=(3, 3))
b = torch.rand(size=(3, 3))

In [44]:
a

tensor([[0.8322, 0.8629, 0.1062],
        [0.7747, 0.0017, 0.4262],
        [0.8406, 0.3604, 0.8764]])

In [45]:
b

tensor([[0.4688, 0.6669, 0.1535],
        [0.1584, 0.6911, 0.3957],
        [0.1947, 0.3910, 0.8002]])

In [46]:
a + 20

tensor([[20.8322, 20.8629, 20.1062],
        [20.7747, 20.0017, 20.4262],
        [20.8406, 20.3604, 20.8764]])

In [47]:
torch.add(a, 10)

tensor([[10.8322, 10.8629, 10.1062],
        [10.7747, 10.0017, 10.4262],
        [10.8406, 10.3604, 10.8764]])

In [48]:
a + b

tensor([[1.3010, 1.5298, 0.2598],
        [0.9331, 0.6929, 0.8219],
        [1.0353, 0.7514, 1.6766]])

In [49]:
a - 10

tensor([[-9.1678, -9.1371, -9.8938],
        [-9.2253, -9.9983, -9.5738],
        [-9.1594, -9.6396, -9.1236]])

In [50]:
torch.sub(a, 10)

tensor([[-9.1678, -9.1371, -9.8938],
        [-9.2253, -9.9983, -9.5738],
        [-9.1594, -9.6396, -9.1236]])

In [51]:
a - b

tensor([[ 0.3634,  0.1961, -0.0473],
        [ 0.6163, -0.6894,  0.0305],
        [ 0.6459, -0.0306,  0.0762]])

In [52]:
a * 10

tensor([[8.3217, 8.6293, 1.0624],
        [7.7471, 0.0172, 4.2616],
        [8.4059, 3.6037, 8.7642]])

In [53]:
torch.mul(a, 10)

tensor([[8.3217, 8.6293, 1.0624],
        [7.7471, 0.0172, 4.2616],
        [8.4059, 3.6037, 8.7642]])

In [54]:
a * b

tensor([[0.3901, 0.5755, 0.0163],
        [0.1227, 0.0012, 0.1686],
        [0.1637, 0.1409, 0.7013]])

In [55]:
a / 10

tensor([[0.0832, 0.0863, 0.0106],
        [0.0775, 0.0002, 0.0426],
        [0.0841, 0.0360, 0.0876]])

In [56]:
torch.div(a, 10)

tensor([[0.0832, 0.0863, 0.0106],
        [0.0775, 0.0002, 0.0426],
        [0.0841, 0.0360, 0.0876]])

In [57]:
a / b

tensor([[1.7751e+00, 1.2940e+00, 6.9201e-01],
        [4.8912e+00, 2.4833e-03, 1.0770e+00],
        [4.3173e+00, 9.2163e-01, 1.0952e+00]])

In [58]:
torch.matmul(a, b)

tensor([[0.5475, 1.1929, 0.5542],
        [0.4464, 0.6845, 0.4606],
        [0.6218, 1.1523, 0.9730]])

In [59]:
a @ b

tensor([[0.5475, 1.1929, 0.5542],
        [0.4464, 0.6845, 0.4606],
        [0.6218, 1.1523, 0.9730]])

In [60]:
a ** 2

tensor([[6.9251e-01, 7.4465e-01, 1.1287e-02],
        [6.0017e-01, 2.9457e-06, 1.8161e-01],
        [7.0659e-01, 1.2986e-01, 7.6811e-01]])

In [61]:
a ** (1 / 2)

tensor([[0.9122, 0.9289, 0.3259],
        [0.8802, 0.0414, 0.6528],
        [0.9168, 0.6003, 0.9362]])

In [62]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([1, 2, 3])

In [63]:
%%time
value = 0
for i in range(len(tensor)):
    value += a[i] + b[i]
value

CPU times: user 116 μs, sys: 25 μs, total: 141 μs
Wall time: 147 μs


tensor(2)

In [64]:
%%time
torch.matmul(a, b)

CPU times: user 594 μs, sys: 1.19 ms, total: 1.78 ms
Wall time: 1.19 ms


tensor(14)

In [65]:
%%time
a @ b

CPU times: user 37 μs, sys: 7 μs, total: 44 μs
Wall time: 48.2 μs


tensor(14)

In [66]:
torch.rand([3, 2]) @ torch.rand([3, 2])

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [67]:
torch.rand([3, 2]) @ torch.rand([2, 3])

tensor([[0.1792, 0.0845, 0.9678],
        [0.3586, 0.1265, 1.4809],
        [0.3186, 0.1221, 1.4194]])

In [68]:
torch.rand([2, 3]) @ torch.rand([3, 2])

tensor([[1.0994, 1.1815],
        [1.7455, 1.0099]])

In [69]:
a = torch.rand([4, 3])
a

tensor([[0.9159, 0.3542, 0.1957],
        [0.7924, 0.8684, 0.4709],
        [0.8384, 0.6378, 0.5718],
        [0.7424, 0.6263, 0.8524]])

In [70]:
b = a.T
b

tensor([[0.9159, 0.7924, 0.8384, 0.7424],
        [0.3542, 0.8684, 0.6378, 0.6263],
        [0.1957, 0.4709, 0.5718, 0.8524]])

In [71]:
a.shape, b.shape

(torch.Size([4, 3]), torch.Size([3, 4]))

In [72]:
b.T

tensor([[0.9159, 0.3542, 0.1957],
        [0.7924, 0.8684, 0.4709],
        [0.8384, 0.6378, 0.5718],
        [0.7424, 0.6263, 0.8524]])

In [73]:
torch.mm(a, a.T)

tensor([[1.0026, 1.1255, 1.1057, 1.0686],
        [1.1255, 1.6038, 1.4875, 1.5336],
        [1.1057, 1.4875, 1.4367, 1.5093],
        [1.0686, 1.5336, 1.5093, 1.6700]])

### Tensor aggregation

In [80]:
tensor = torch.arange(0, 100, 10)
tensor, tensor.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [77]:
torch.min(tensor), tensor.min()

(tensor(0), tensor(0))

In [78]:
torch.max(tensor), tensor.max()

(tensor(90), tensor(90))

In [82]:
torch.mean(tensor.type(torch.float32)), tensor.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [83]:
torch.sum(tensor), tensor.sum()

(tensor(450), tensor(450))

### Finiding positions

In [86]:
tensor

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [84]:
torch.argmax(tensor), tensor.argmax()

(tensor(9), tensor(9))

In [87]:
tensor[tensor.argmax()]

tensor(90)

In [85]:
torch.argmin(tensor), tensor.argmin()

(tensor(0), tensor(0))

In [88]:
tensor[torch.argmin(tensor)]

tensor(0)

### Reshaping, starcking, squeezing and unsqueezing tensors

In [90]:
a = torch.rand(size=[3, 5])
a

tensor([[0.1637, 0.5733, 0.5623, 0.6498, 0.2153],
        [0.4352, 0.4406, 0.6680, 0.5569, 0.0643],
        [0.2426, 0.5575, 0.8442, 0.8379, 0.2307]])

In [91]:
a.shape

torch.Size([3, 5])

In [100]:
a_reshaped = a.reshape(1, 15)
a_reshaped, a_reshaped.shape

(tensor([[0.1637, 0.5733, 0.5623, 0.6498, 0.2153, 0.4352, 0.4406, 0.6680, 0.5569,
          0.0643, 0.2426, 0.5575, 0.8442, 0.8379, 0.2307]]),
 torch.Size([1, 15]))

In [101]:
a_reshaped = a.reshape(5, 3)
a_reshaped, a_reshaped.shape

(tensor([[0.1637, 0.5733, 0.5623],
         [0.6498, 0.2153, 0.4352],
         [0.4406, 0.6680, 0.5569],
         [0.0643, 0.2426, 0.5575],
         [0.8442, 0.8379, 0.2307]]),
 torch.Size([5, 3]))

In [102]:
a_reshaped = a.reshape(15, 1)
a_reshaped, a_reshaped.shape

(tensor([[0.1637],
         [0.5733],
         [0.5623],
         [0.6498],
         [0.2153],
         [0.4352],
         [0.4406],
         [0.6680],
         [0.5569],
         [0.0643],
         [0.2426],
         [0.5575],
         [0.8442],
         [0.8379],
         [0.2307]]),
 torch.Size([15, 1]))

In [ ]:
b = a.view(3, 5) # chaning b changes a - a view of a tensor shares the same memory as the original input
b, b.shape

(tensor([[0.1637, 0.5733, 0.5623, 0.6498, 0.2153],
         [0.4352, 0.4406, 0.6680, 0.5569, 0.0643],
         [0.2426, 0.5575, 0.8442, 0.8379, 0.2307]]),
 torch.Size([3, 5]))

In [108]:
b[0][0] = 19
a, b

(tensor([[19.0000, 19.0000,  0.5623,  0.6498,  0.2153],
         [ 0.4352,  0.4406,  0.6680,  0.5569,  0.0643],
         [ 0.2426,  0.5575,  0.8442,  0.8379,  0.2307]]),
 tensor([[19.0000, 19.0000,  0.5623,  0.6498,  0.2153],
         [ 0.4352,  0.4406,  0.6680,  0.5569,  0.0643],
         [ 0.2426,  0.5575,  0.8442,  0.8379,  0.2307]]))

In [109]:
a_stacked = torch.stack([a, a, a, a], dim=0)
a_stacked

tensor([[[19.0000, 19.0000,  0.5623,  0.6498,  0.2153],
         [ 0.4352,  0.4406,  0.6680,  0.5569,  0.0643],
         [ 0.2426,  0.5575,  0.8442,  0.8379,  0.2307]],

        [[19.0000, 19.0000,  0.5623,  0.6498,  0.2153],
         [ 0.4352,  0.4406,  0.6680,  0.5569,  0.0643],
         [ 0.2426,  0.5575,  0.8442,  0.8379,  0.2307]],

        [[19.0000, 19.0000,  0.5623,  0.6498,  0.2153],
         [ 0.4352,  0.4406,  0.6680,  0.5569,  0.0643],
         [ 0.2426,  0.5575,  0.8442,  0.8379,  0.2307]],

        [[19.0000, 19.0000,  0.5623,  0.6498,  0.2153],
         [ 0.4352,  0.4406,  0.6680,  0.5569,  0.0643],
         [ 0.2426,  0.5575,  0.8442,  0.8379,  0.2307]]])

In [110]:
a_stacked = torch.stack([a, a, a, a], dim=1)
a_stacked

tensor([[[19.0000, 19.0000,  0.5623,  0.6498,  0.2153],
         [19.0000, 19.0000,  0.5623,  0.6498,  0.2153],
         [19.0000, 19.0000,  0.5623,  0.6498,  0.2153],
         [19.0000, 19.0000,  0.5623,  0.6498,  0.2153]],

        [[ 0.4352,  0.4406,  0.6680,  0.5569,  0.0643],
         [ 0.4352,  0.4406,  0.6680,  0.5569,  0.0643],
         [ 0.4352,  0.4406,  0.6680,  0.5569,  0.0643],
         [ 0.4352,  0.4406,  0.6680,  0.5569,  0.0643]],

        [[ 0.2426,  0.5575,  0.8442,  0.8379,  0.2307],
         [ 0.2426,  0.5575,  0.8442,  0.8379,  0.2307],
         [ 0.2426,  0.5575,  0.8442,  0.8379,  0.2307],
         [ 0.2426,  0.5575,  0.8442,  0.8379,  0.2307]]])

In [119]:
b = torch.rand(size=[1, 1, 3])
b, b.shape

(tensor([[[0.5032, 0.9342, 0.5729]]]), torch.Size([1, 1, 3]))

In [122]:
c = b.squeeze()
c, c.shape

(tensor([0.5032, 0.9342, 0.5729]), torch.Size([3]))

In [127]:
d = c.unsqueeze(dim=0).unsqueeze(dim=0)
d, d.shape

(tensor([[[0.5032, 0.9342, 0.5729]]]), torch.Size([1, 1, 3]))

In [129]:
e = c.unsqueeze(dim=-2)
e, e.shape

(tensor([[0.5032, 0.9342, 0.5729]]), torch.Size([1, 3]))

In [131]:
f = c.unsqueeze(dim=1)
f, f.shape

(tensor([[0.5032],
         [0.9342],
         [0.5729]]),
 torch.Size([3, 1]))

In [134]:
y = torch.rand(size=(224, 224, 3))
y, y.shape

(tensor([[[0.0940, 0.3308, 0.8919],
          [0.8775, 0.4826, 0.6377],
          [0.6533, 0.5490, 0.7981],
          ...,
          [0.4844, 0.1111, 0.4884],
          [0.2140, 0.4797, 0.8995],
          [0.8036, 0.5318, 0.2188]],
 
         [[0.1062, 0.9507, 0.6354],
          [0.2769, 0.5269, 0.5970],
          [0.4646, 0.6012, 0.3301],
          ...,
          [0.7391, 0.8804, 0.4651],
          [0.3475, 0.1501, 0.7923],
          [0.1009, 0.3170, 0.7256]],
 
         [[0.4053, 0.1485, 0.8565],
          [0.2042, 0.7752, 0.6535],
          [0.7438, 0.6963, 0.9354],
          ...,
          [0.7185, 0.6266, 0.0259],
          [0.8534, 0.8278, 0.6321],
          [0.7207, 0.8888, 0.7017]],
 
         ...,
 
         [[0.3789, 0.1034, 0.7356],
          [0.9113, 0.6219, 0.1620],
          [0.2701, 0.5990, 0.4077],
          ...,
          [0.0103, 0.7444, 0.2604],
          [0.9726, 0.4518, 0.8826],
          [0.2691, 0.8161, 0.1025]],
 
         [[0.6089, 0.0661, 0.0293],
          [0

In [140]:
z = y.permute((2, 0, 1))
z, z.shape

(tensor([[[0.0940, 0.8775, 0.6533,  ..., 0.4844, 0.2140, 0.8036],
          [0.1062, 0.2769, 0.4646,  ..., 0.7391, 0.3475, 0.1009],
          [0.4053, 0.2042, 0.7438,  ..., 0.7185, 0.8534, 0.7207],
          ...,
          [0.3789, 0.9113, 0.2701,  ..., 0.0103, 0.9726, 0.2691],
          [0.6089, 0.8705, 0.5669,  ..., 0.1768, 0.5972, 0.4586],
          [0.9704, 0.7565, 0.4853,  ..., 0.8906, 0.8181, 0.2227]],
 
         [[0.3308, 0.4826, 0.5490,  ..., 0.1111, 0.4797, 0.5318],
          [0.9507, 0.5269, 0.6012,  ..., 0.8804, 0.1501, 0.3170],
          [0.1485, 0.7752, 0.6963,  ..., 0.6266, 0.8278, 0.8888],
          ...,
          [0.1034, 0.6219, 0.5990,  ..., 0.7444, 0.4518, 0.8161],
          [0.0661, 0.0684, 0.7318,  ..., 0.1944, 0.4968, 0.2009],
          [0.3137, 0.6765, 0.7386,  ..., 0.6687, 0.8829, 0.8745]],
 
         [[0.8919, 0.6377, 0.7981,  ..., 0.4884, 0.8995, 0.2188],
          [0.6354, 0.5970, 0.3301,  ..., 0.4651, 0.7923, 0.7256],
          [0.8565, 0.6535, 0.9354,  ...,