# 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.7.1


## Introduction to Tensors

Link: https://docs.pytorch.org/docs/stable/tensors.html

### Creating tensors

In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# matrix
matrix = torch.tensor([[7, 8], 
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
matrix.ndim

2

In [11]:
matrix.shape

torch.Size([2, 2])

In [12]:
matrix[0]

tensor([7, 8])

In [13]:
matrix[1]

tensor([ 9, 10])

In [14]:
# tensor
tensor = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [15]:
tensor.ndim

3

In [16]:
tensor.shape

torch.Size([1, 3, 3])

In [17]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [18]:
tensor[0][1]

tensor([4, 5, 6])

In [19]:
tensor[0][1][2]

tensor(6)

### Random tensors

In [20]:
# Create a random tensor of size / shape (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6869, 0.4846, 0.1864, 0.3579],
        [0.2866, 0.8728, 0.6828, 0.1713],
        [0.7771, 0.5591, 0.8641, 0.7686]])

In [21]:
random_tensor.ndim

2

In [22]:
random_tensor = torch.rand(3, 3, 3)
random_tensor

tensor([[[0.1689, 0.4022, 0.3806],
         [0.0050, 0.6690, 0.9851],
         [0.6915, 0.6308, 0.2730]],

        [[0.3535, 0.0875, 0.7243],
         [0.6584, 0.7245, 0.7163],
         [0.1230, 0.1688, 0.1537]],

        [[0.2314, 0.6647, 0.1766],
         [0.9320, 0.3840, 0.4957],
         [0.4870, 0.5938, 0.6958]]])

In [23]:
torch.rand(size=(1, 2, 3))

tensor([[[0.3752, 0.1266, 0.9738],
         [0.2583, 0.1045, 0.6233]]])

In [24]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [25]:
random_tensor = torch.rand(size=(3, 4))
random_tensor

tensor([[0.4638, 0.0918, 0.1664, 0.2505],
        [0.2235, 0.5241, 0.1086, 0.6499],
        [0.1203, 0.5928, 0.1143, 0.6991]])

In [26]:
# tensor of zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
# tensor of ones
ones = torch.ones(size=(3, 4))

In [29]:
ones.dtype

torch.float32

In [30]:
ones * random_tensor

tensor([[0.4638, 0.0918, 0.1664, 0.2505],
        [0.2235, 0.5241, 0.1086, 0.6499],
        [0.1203, 0.5928, 0.1143, 0.6991]])

### Creating a range of tensors and tensors-like

In [31]:
torch.range(2, 8)

/var/folders/zd/7ryz379j2dz9shhk8m8k4zx40000gn/T/ipykernel_16459/616276269.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(2, 8)


tensor([2., 3., 4., 5., 6., 7., 8.])

In [32]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
one_to_ten = torch.arange(1, 11)

In [34]:
torch.arange(start=0, end=1000, step=99)

tensor([  0,  99, 198, 297, 396, 495, 594, 693, 792, 891, 990])

In [35]:
ten_zeres = torch.zeros_like(input=one_to_ten)
ten_zeres

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [36]:
float_32_tensor = torch.tensor([3.0 , 6.0, 9.0], 
                               dtype=torch.float32)
float_32_tensor.dtype

torch.float32

In [37]:
float_16_tensor = torch.tensor([3.0 , 6.0, 9.0], 
                               dtype=torch.float16, # datatype of tensor
                               device="mps",
                               requires_grad=False)
float_16_tensor.dtype

torch.float16

In [38]:
float_64_tensor = float_32_tensor.type(torch.float64)
float_64_tensor

tensor([3., 6., 9.], dtype=torch.float64)

In [39]:
float_16_tensor.shape, float_16_tensor.device, float_16_tensor.dtype

(torch.Size([3]), device(type='mps', index=0), torch.float16)

In [40]:
float_64_tensor * float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float64)

In [41]:
float_32_tensor * float_64_tensor

tensor([ 9., 36., 81.], dtype=torch.float64)

In [42]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [43]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Manipulating tensors

In [44]:
a = torch.rand(size=(3, 3))
b = torch.rand(size=(3, 3))

In [45]:
a

tensor([[0.7788, 0.6335, 0.4818],
        [0.4589, 0.3148, 0.8821],
        [0.6855, 0.6127, 0.8287]])

In [46]:
b

tensor([[0.5112, 0.0920, 0.4313],
        [0.3756, 0.1527, 0.7083],
        [0.2629, 0.9744, 0.4822]])

In [47]:
a + 20

tensor([[20.7788, 20.6335, 20.4818],
        [20.4589, 20.3148, 20.8821],
        [20.6855, 20.6127, 20.8287]])

In [48]:
torch.add(a, 10)

tensor([[10.7788, 10.6335, 10.4818],
        [10.4589, 10.3148, 10.8821],
        [10.6855, 10.6127, 10.8287]])

In [49]:
a + b

tensor([[1.2900, 0.7255, 0.9131],
        [0.8345, 0.4675, 1.5905],
        [0.9484, 1.5871, 1.3109]])

In [50]:
a - 10

tensor([[-9.2212, -9.3665, -9.5182],
        [-9.5411, -9.6852, -9.1179],
        [-9.3145, -9.3873, -9.1713]])

In [51]:
torch.sub(a, 10)

tensor([[-9.2212, -9.3665, -9.5182],
        [-9.5411, -9.6852, -9.1179],
        [-9.3145, -9.3873, -9.1713]])

In [52]:
a - b

tensor([[ 0.2675,  0.5415,  0.0505],
        [ 0.0833,  0.1621,  0.1738],
        [ 0.4225, -0.3617,  0.3465]])

In [53]:
a * 10

tensor([[7.7877, 6.3350, 4.8180],
        [4.5888, 3.1482, 8.8211],
        [6.8546, 6.1271, 8.2866]])

In [54]:
torch.mul(a, 10)

tensor([[7.7877, 6.3350, 4.8180],
        [4.5888, 3.1482, 8.8211],
        [6.8546, 6.1271, 8.2866]])

In [55]:
a * b

tensor([[0.3981, 0.0583, 0.2078],
        [0.1723, 0.0481, 0.6248],
        [0.1802, 0.5970, 0.3996]])

In [56]:
a / 10

tensor([[0.0779, 0.0633, 0.0482],
        [0.0459, 0.0315, 0.0882],
        [0.0685, 0.0613, 0.0829]])

In [57]:
torch.div(a, 10)

tensor([[0.0779, 0.0633, 0.0482],
        [0.0459, 0.0315, 0.0882],
        [0.0685, 0.0613, 0.0829]])

In [58]:
a / b

tensor([[1.5233, 6.8855, 1.1170],
        [1.2218, 2.0618, 1.2453],
        [2.6070, 0.6288, 1.7185]])

In [59]:
torch.matmul(a, b)

tensor([[0.7627, 0.6379, 1.0170],
        [0.5848, 0.9498, 0.8463],
        [0.7984, 0.9641, 1.1292]])

In [60]:
a @ b

tensor([[0.7627, 0.6379, 1.0170],
        [0.5848, 0.9498, 0.8463],
        [0.7984, 0.9641, 1.1292]])

In [61]:
a ** 2

tensor([[0.6065, 0.4013, 0.2321],
        [0.2106, 0.0991, 0.7781],
        [0.4699, 0.3754, 0.6867]])

In [62]:
a ** (1 / 2)

tensor([[0.8825, 0.7959, 0.6941],
        [0.6774, 0.5611, 0.9392],
        [0.8279, 0.7828, 0.9103]])

In [63]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([1, 2, 3])

In [64]:
%%time
value = 0
for i in range(len(tensor)):
    value += a[i] + b[i]
value

CPU times: user 128 μs, sys: 8 μs, total: 136 μs
Wall time: 149 μs


tensor(2)

In [65]:
%%time
torch.matmul(a, b)

CPU times: user 686 μs, sys: 967 μs, total: 1.65 ms
Wall time: 1.07 ms


tensor(14)

In [66]:
%%time
a @ b

CPU times: user 172 μs, sys: 87 μs, total: 259 μs
Wall time: 316 μs


tensor(14)

In [67]:
torch.rand([3, 2]) @ torch.rand([3, 2])

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [68]:
torch.rand([3, 2]) @ torch.rand([2, 3])

tensor([[0.8174, 0.1542, 0.4586],
        [0.3415, 0.3195, 0.4275],
        [0.5816, 0.1993, 0.4091]])

In [69]:
torch.rand([2, 3]) @ torch.rand([3, 2])

tensor([[0.2331, 0.6071],
        [0.2846, 0.8141]])

In [70]:
a = torch.rand([4, 3])
a

tensor([[0.7832, 0.1297, 0.3613],
        [0.0096, 0.9618, 0.5739],
        [0.7290, 0.7452, 0.8634],
        [0.7764, 0.9741, 0.0931]])

In [71]:
b = a.T
b

tensor([[0.7832, 0.0096, 0.7290, 0.7764],
        [0.1297, 0.9618, 0.7452, 0.9741],
        [0.3613, 0.5739, 0.8634, 0.0931]])

In [72]:
a.shape, b.shape

(torch.Size([4, 3]), torch.Size([3, 4]))

In [73]:
b.T

tensor([[0.7832, 0.1297, 0.3613],
        [0.0096, 0.9618, 0.5739],
        [0.7290, 0.7452, 0.8634],
        [0.7764, 0.9741, 0.0931]])

In [74]:
torch.mm(a, a.T)

tensor([[0.7608, 0.3396, 0.9796, 0.7680],
        [0.3396, 1.2545, 1.2192, 0.9978],
        [0.9796, 1.2192, 1.8322, 1.3722],
        [0.7680, 0.9978, 1.3722, 1.5603]])

### Tensor aggregation

In [75]:
tensor = torch.arange(0, 100, 10)
tensor, tensor.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [76]:
torch.min(tensor), tensor.min()

(tensor(0), tensor(0))

In [77]:
torch.max(tensor), tensor.max()

(tensor(90), tensor(90))

In [78]:
torch.mean(tensor.type(torch.float32)), tensor.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [79]:
torch.sum(tensor), tensor.sum()

(tensor(450), tensor(450))

### Finiding positions

In [80]:
tensor

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [81]:
torch.argmax(tensor), tensor.argmax()

(tensor(9), tensor(9))

In [82]:
tensor[tensor.argmax()]

tensor(90)

In [83]:
torch.argmin(tensor), tensor.argmin()

(tensor(0), tensor(0))

In [84]:
tensor[torch.argmin(tensor)]

tensor(0)

### Reshaping, starcking, squeezing and unsqueezing tensors

In [85]:
a = torch.rand(size=[3, 5])
a

tensor([[0.1852, 0.5829, 0.5286, 0.6473, 0.6967],
        [0.7241, 0.9977, 0.7668, 0.5249, 0.2183],
        [0.9343, 0.2792, 0.9495, 0.3656, 0.4781]])

In [86]:
a.shape

torch.Size([3, 5])

In [87]:
a_reshaped = a.reshape(1, 15)
a_reshaped, a_reshaped.shape

(tensor([[0.1852, 0.5829, 0.5286, 0.6473, 0.6967, 0.7241, 0.9977, 0.7668, 0.5249,
          0.2183, 0.9343, 0.2792, 0.9495, 0.3656, 0.4781]]),
 torch.Size([1, 15]))

In [88]:
a_reshaped = a.reshape(5, 3)
a_reshaped, a_reshaped.shape

(tensor([[0.1852, 0.5829, 0.5286],
         [0.6473, 0.6967, 0.7241],
         [0.9977, 0.7668, 0.5249],
         [0.2183, 0.9343, 0.2792],
         [0.9495, 0.3656, 0.4781]]),
 torch.Size([5, 3]))

In [89]:
a_reshaped = a.reshape(15, 1)
a_reshaped, a_reshaped.shape

(tensor([[0.1852],
         [0.5829],
         [0.5286],
         [0.6473],
         [0.6967],
         [0.7241],
         [0.9977],
         [0.7668],
         [0.5249],
         [0.2183],
         [0.9343],
         [0.2792],
         [0.9495],
         [0.3656],
         [0.4781]]),
 torch.Size([15, 1]))

In [90]:
b = a.view(3, 5) # chaning b changes a - a view of a tensor shares the same memory as the original input
b, b.shape

(tensor([[0.1852, 0.5829, 0.5286, 0.6473, 0.6967],
         [0.7241, 0.9977, 0.7668, 0.5249, 0.2183],
         [0.9343, 0.2792, 0.9495, 0.3656, 0.4781]]),
 torch.Size([3, 5]))

In [91]:
b[0][0] = 19
a, b

(tensor([[19.0000,  0.5829,  0.5286,  0.6473,  0.6967],
         [ 0.7241,  0.9977,  0.7668,  0.5249,  0.2183],
         [ 0.9343,  0.2792,  0.9495,  0.3656,  0.4781]]),
 tensor([[19.0000,  0.5829,  0.5286,  0.6473,  0.6967],
         [ 0.7241,  0.9977,  0.7668,  0.5249,  0.2183],
         [ 0.9343,  0.2792,  0.9495,  0.3656,  0.4781]]))

In [92]:
a_stacked = torch.stack([a, a, a, a], dim=0)
a_stacked

tensor([[[19.0000,  0.5829,  0.5286,  0.6473,  0.6967],
         [ 0.7241,  0.9977,  0.7668,  0.5249,  0.2183],
         [ 0.9343,  0.2792,  0.9495,  0.3656,  0.4781]],

        [[19.0000,  0.5829,  0.5286,  0.6473,  0.6967],
         [ 0.7241,  0.9977,  0.7668,  0.5249,  0.2183],
         [ 0.9343,  0.2792,  0.9495,  0.3656,  0.4781]],

        [[19.0000,  0.5829,  0.5286,  0.6473,  0.6967],
         [ 0.7241,  0.9977,  0.7668,  0.5249,  0.2183],
         [ 0.9343,  0.2792,  0.9495,  0.3656,  0.4781]],

        [[19.0000,  0.5829,  0.5286,  0.6473,  0.6967],
         [ 0.7241,  0.9977,  0.7668,  0.5249,  0.2183],
         [ 0.9343,  0.2792,  0.9495,  0.3656,  0.4781]]])

In [93]:
a_stacked = torch.stack([a, a, a, a], dim=1)
a_stacked

tensor([[[19.0000,  0.5829,  0.5286,  0.6473,  0.6967],
         [19.0000,  0.5829,  0.5286,  0.6473,  0.6967],
         [19.0000,  0.5829,  0.5286,  0.6473,  0.6967],
         [19.0000,  0.5829,  0.5286,  0.6473,  0.6967]],

        [[ 0.7241,  0.9977,  0.7668,  0.5249,  0.2183],
         [ 0.7241,  0.9977,  0.7668,  0.5249,  0.2183],
         [ 0.7241,  0.9977,  0.7668,  0.5249,  0.2183],
         [ 0.7241,  0.9977,  0.7668,  0.5249,  0.2183]],

        [[ 0.9343,  0.2792,  0.9495,  0.3656,  0.4781],
         [ 0.9343,  0.2792,  0.9495,  0.3656,  0.4781],
         [ 0.9343,  0.2792,  0.9495,  0.3656,  0.4781],
         [ 0.9343,  0.2792,  0.9495,  0.3656,  0.4781]]])

In [94]:
b = torch.rand(size=[1, 1, 3])
b, b.shape

(tensor([[[0.5994, 0.3387, 0.5882]]]), torch.Size([1, 1, 3]))

In [95]:
c = b.squeeze()
c, c.shape

(tensor([0.5994, 0.3387, 0.5882]), torch.Size([3]))

In [96]:
d = c.unsqueeze(dim=0).unsqueeze(dim=0)
d, d.shape

(tensor([[[0.5994, 0.3387, 0.5882]]]), torch.Size([1, 1, 3]))

In [97]:
e = c.unsqueeze(dim=-2)
e, e.shape

(tensor([[0.5994, 0.3387, 0.5882]]), torch.Size([1, 3]))

In [98]:
f = c.unsqueeze(dim=1)
f, f.shape

(tensor([[0.5994],
         [0.3387],
         [0.5882]]),
 torch.Size([3, 1]))

In [99]:
y = torch.rand(size=(224, 224, 3))
y, y.shape

(tensor([[[0.4724, 0.3281, 0.0502],
          [0.1445, 0.2244, 0.0021],
          [0.4027, 0.9660, 0.2088],
          ...,
          [0.5808, 0.4106, 0.4681],
          [0.3356, 0.6794, 0.9941],
          [0.0417, 0.1593, 0.2971]],
 
         [[0.0754, 0.1007, 0.9744],
          [0.3733, 0.4563, 0.0696],
          [0.7315, 0.8633, 0.6857],
          ...,
          [0.4479, 0.3472, 0.7181],
          [0.9222, 0.0855, 0.1397],
          [0.7774, 0.6452, 0.5164]],
 
         [[0.2504, 0.5608, 0.1630],
          [0.2466, 0.4437, 0.5283],
          [0.5515, 0.7292, 0.7915],
          ...,
          [0.8226, 0.5506, 0.8610],
          [0.4809, 0.6766, 0.3340],
          [0.3655, 0.8958, 0.4750]],
 
         ...,
 
         [[0.4395, 0.7901, 0.1285],
          [0.7694, 0.4237, 0.7932],
          [0.2508, 0.8143, 0.5623],
          ...,
          [0.6131, 0.9482, 0.2400],
          [0.3056, 0.4576, 0.8737],
          [0.7576, 0.0033, 0.7282]],
 
         [[0.5481, 0.0137, 0.5128],
          [0

In [100]:
z = y.permute((2, 0, 1))
z, z.shape

(tensor([[[0.4724, 0.1445, 0.4027,  ..., 0.5808, 0.3356, 0.0417],
          [0.0754, 0.3733, 0.7315,  ..., 0.4479, 0.9222, 0.7774],
          [0.2504, 0.2466, 0.5515,  ..., 0.8226, 0.4809, 0.3655],
          ...,
          [0.4395, 0.7694, 0.2508,  ..., 0.6131, 0.3056, 0.7576],
          [0.5481, 0.0331, 0.1771,  ..., 0.8347, 0.3833, 0.0469],
          [0.8518, 0.1838, 0.2265,  ..., 0.9431, 0.3946, 0.7612]],
 
         [[0.3281, 0.2244, 0.9660,  ..., 0.4106, 0.6794, 0.1593],
          [0.1007, 0.4563, 0.8633,  ..., 0.3472, 0.0855, 0.6452],
          [0.5608, 0.4437, 0.7292,  ..., 0.5506, 0.6766, 0.8958],
          ...,
          [0.7901, 0.4237, 0.8143,  ..., 0.9482, 0.4576, 0.0033],
          [0.0137, 0.6203, 0.9114,  ..., 0.0194, 0.4818, 0.9156],
          [0.1980, 0.4205, 0.6046,  ..., 0.0624, 0.8781, 0.9763]],
 
         [[0.0502, 0.0021, 0.2088,  ..., 0.4681, 0.9941, 0.2971],
          [0.9744, 0.0696, 0.6857,  ..., 0.7181, 0.1397, 0.5164],
          [0.1630, 0.5283, 0.7915,  ...,

### Indexing

In [101]:
x = torch.arange(1, 10, 1)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
y = x.reshape(1, 3, 3)
y

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [103]:
y[0, 0, 0], y[0, 0, 1], y[0, 0, 2]

(tensor(1), tensor(2), tensor(3))

In [104]:
y[0, 1]

tensor([4, 5, 6])

In [105]:
y[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [106]:
y[0, 1, :2]

tensor([4, 5])

In [107]:
y[0, 1, 1:]

tensor([5, 6])

In [108]:
y[0][0]

tensor([1, 2, 3])

In [109]:
y[0][1][1:]

tensor([5, 6])

In [110]:
y[0][0][0] = 10

In [111]:
y, x

(tensor([[[10,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]]]),
 tensor([10,  2,  3,  4,  5,  6,  7,  8,  9]))

In [112]:
y[:, :, 1]

tensor([[2, 5, 8]])

In [113]:
y[:, :, 0]

tensor([[10,  4,  7]])

In [114]:
y[0][0], y[0, 0, :]

(tensor([10,  2,  3]), tensor([10,  2,  3]))

In [115]:
y[0][2][-1]

tensor(9)

In [116]:
y[:, :, 2]

tensor([[3, 6, 9]])

## PyTorch and NumPy

In [117]:
array = np.arange(1, 10)
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [118]:
tensor = torch.from_numpy(array)
tensor

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
array = array + 1
array, tensor

(array([ 2,  3,  4,  5,  6,  7,  8,  9, 10]),
 tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [120]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [121]:
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility

In [127]:
random_a = torch.rand(3, 3)
random_b = torch.rand(3, 3)

In [128]:
random_a, random_b

(tensor([[0.5739, 0.1237, 0.0209],
         [0.7785, 0.3104, 0.2498],
         [0.6883, 0.8590, 0.0126]]),
 tensor([[0.2173, 0.5775, 0.6385],
         [0.0626, 0.6966, 0.6447],
         [0.1234, 0.5076, 0.9332]]))

In [129]:
random_a == random_b

tensor([[False, False, False],
        [False, False, False],
        [False, False, False]])

In [133]:
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_c = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_d = torch.rand(3, 4)

random_c, random_d

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]))

In [134]:
random_c == random_d

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

## Running tensors and PyTorch objects on the GPUs