## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.7.1


## Introduction to Tensors

Link: https://docs.pytorch.org/docs/stable/tensors.html

### Creating tensors

In [2]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
# vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# matrix
matrix = torch.tensor([[7, 8], 
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
matrix.ndim

2

In [10]:
matrix.shape

torch.Size([2, 2])

In [11]:
matrix[0]

tensor([7, 8])

In [12]:
matrix[1]

tensor([ 9, 10])

In [13]:
# tensor
tensor = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
tensor.ndim

3

In [15]:
tensor.shape

torch.Size([1, 3, 3])

In [16]:
tensor[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [17]:
tensor[0][1]

tensor([4, 5, 6])

In [18]:
tensor[0][1][2]

tensor(6)

### Random tensors

In [19]:
# Create a random tensor of size / shape (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6551, 0.5438, 0.8638, 0.1416],
        [0.0204, 0.1553, 0.3455, 0.5955],
        [0.5012, 0.1305, 0.1003, 0.7081]])

In [20]:
random_tensor.ndim

2

In [21]:
random_tensor = torch.rand(3, 3, 3)
random_tensor

tensor([[[0.4870, 0.5068, 0.8089],
         [0.7105, 0.1388, 0.7742],
         [0.2657, 0.5445, 0.8870]],

        [[0.9572, 0.0644, 0.4747],
         [0.3741, 0.7827, 0.5871],
         [0.5894, 0.2703, 0.4045]],

        [[0.6148, 0.2353, 0.0144],
         [0.9210, 0.6908, 0.9307],
         [0.6980, 0.0740, 0.4305]]])

In [22]:
torch.rand(size=(1, 2, 3))

tensor([[[0.0622, 0.0372, 0.0103],
         [0.2011, 0.0460, 0.3823]]])

In [23]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [24]:
random_tensor = torch.rand(size=(3, 4))
random_tensor

tensor([[0.9123, 0.2045, 0.3954, 0.6091],
        [0.7200, 0.8935, 0.8104, 0.8401],
        [0.7576, 0.1363, 0.6206, 0.0450]])

In [25]:
# tensor of zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
# tensor of ones
ones = torch.ones(size=(3, 4))

In [28]:
ones.dtype

torch.float32

In [29]:
ones * random_tensor

tensor([[0.9123, 0.2045, 0.3954, 0.6091],
        [0.7200, 0.8935, 0.8104, 0.8401],
        [0.7576, 0.1363, 0.6206, 0.0450]])

### Creating a range of tensors and tensors-like

In [30]:
torch.range(2, 8)

/var/folders/zd/7ryz379j2dz9shhk8m8k4zx40000gn/T/ipykernel_38473/616276269.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(2, 8)


tensor([2., 3., 4., 5., 6., 7., 8.])

In [31]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
one_to_ten = torch.arange(1, 11)

In [33]:
torch.arange(start=0, end=1000, step=99)

tensor([  0,  99, 198, 297, 396, 495, 594, 693, 792, 891, 990])

In [34]:
ten_zeres = torch.zeros_like(input=one_to_ten)
ten_zeres

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

In [35]:
float_32_tensor = torch.tensor([3.0 , 6.0, 9.0], 
                               dtype=torch.float32)
float_32_tensor.dtype

torch.float32

In [36]:
float_16_tensor = torch.tensor([3.0 , 6.0, 9.0], 
                               dtype=torch.float16, # datatype of tensor
                               device="mps",
                               requires_grad=False)
float_16_tensor.dtype

torch.float16

In [37]:
float_64_tensor = float_32_tensor.type(torch.float64)
float_64_tensor

tensor([3., 6., 9.], dtype=torch.float64)

In [38]:
float_16_tensor.shape, float_16_tensor.device, float_16_tensor.dtype

(torch.Size([3]), device(type='mps', index=0), torch.float16)

In [39]:
float_64_tensor * float_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float64)

In [40]:
float_32_tensor * float_64_tensor

tensor([ 9., 36., 81.], dtype=torch.float64)

In [41]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [42]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Manipulating tensors

In [43]:
a = torch.rand(size=(3, 3))
b = torch.rand(size=(3, 3))

In [44]:
a

tensor([[0.5865, 0.2554, 0.2946],
        [0.9365, 0.3752, 0.3254],
        [0.3701, 0.8313, 0.2761]])

In [45]:
b

tensor([[0.7378, 0.5291, 0.8065],
        [0.3776, 0.7912, 0.3450],
        [0.3721, 0.4986, 0.3563]])

In [46]:
a + 20

tensor([[20.5865, 20.2554, 20.2946],
        [20.9365, 20.3752, 20.3254],
        [20.3701, 20.8312, 20.2761]])

In [47]:
torch.add(a, 10)

tensor([[10.5865, 10.2554, 10.2946],
        [10.9365, 10.3752, 10.3254],
        [10.3701, 10.8313, 10.2761]])

In [48]:
a + b

tensor([[1.3243, 0.7845, 1.1011],
        [1.3141, 1.1665, 0.6704],
        [0.7422, 1.3299, 0.6323]])

In [49]:
a - 10

tensor([[-9.4135, -9.7446, -9.7054],
        [-9.0635, -9.6248, -9.6746],
        [-9.6299, -9.1687, -9.7239]])

In [50]:
torch.sub(a, 10)

tensor([[-9.4135, -9.7446, -9.7054],
        [-9.0635, -9.6248, -9.6746],
        [-9.6299, -9.1687, -9.7239]])

In [51]:
a - b

tensor([[-0.1513, -0.2737, -0.5119],
        [ 0.5589, -0.4160, -0.0196],
        [-0.0021,  0.3326, -0.0802]])

In [52]:
a * 10

tensor([[5.8646, 2.5540, 2.9460],
        [9.3648, 3.7524, 3.2539],
        [3.7006, 8.3125, 2.7608]])

In [53]:
torch.mul(a, 10)

tensor([[5.8646, 2.5540, 2.9460],
        [9.3648, 3.7524, 3.2539],
        [3.7006, 8.3125, 2.7608]])

In [54]:
a * b

tensor([[0.4327, 0.1351, 0.2376],
        [0.3536, 0.2969, 0.1123],
        [0.1377, 0.4145, 0.0984]])

In [55]:
a / 10

tensor([[0.0586, 0.0255, 0.0295],
        [0.0936, 0.0375, 0.0325],
        [0.0370, 0.0831, 0.0276]])

In [56]:
torch.div(a, 10)

tensor([[0.0586, 0.0255, 0.0295],
        [0.0936, 0.0375, 0.0325],
        [0.0370, 0.0831, 0.0276]])

In [57]:
a / b

tensor([[0.7949, 0.4827, 0.3653],
        [2.4801, 0.4742, 0.9431],
        [0.9944, 1.6671, 0.7749]])

In [58]:
torch.matmul(a, b)

tensor([[0.6388, 0.6592, 0.6660],
        [0.9537, 0.9546, 1.0006],
        [0.6897, 0.9912, 0.6836]])

In [59]:
a @ b

tensor([[0.6388, 0.6592, 0.6660],
        [0.9537, 0.9546, 1.0006],
        [0.6897, 0.9912, 0.6836]])

In [60]:
a ** 2

tensor([[0.3439, 0.0652, 0.0868],
        [0.8770, 0.1408, 0.1059],
        [0.1369, 0.6910, 0.0762]])

In [61]:
a ** (1 / 2)

tensor([[0.7658, 0.5054, 0.5428],
        [0.9677, 0.6126, 0.5704],
        [0.6083, 0.9117, 0.5254]])

In [62]:
a = torch.tensor([1, 2, 3])
b = torch.tensor([1, 2, 3])

In [63]:
%%time
value = 0
for i in range(len(tensor)):
    value += a[i] + b[i]
value

CPU times: user 420 μs, sys: 188 μs, total: 608 μs
Wall time: 548 μs


tensor(2)

In [64]:
%%time
torch.matmul(a, b)

CPU times: user 650 μs, sys: 978 μs, total: 1.63 ms
Wall time: 948 μs


tensor(14)

In [65]:
%%time
a @ b

CPU times: user 42 μs, sys: 13 μs, total: 55 μs
Wall time: 110 μs


tensor(14)

In [66]:
torch.rand([3, 2]) @ torch.rand([3, 2])

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [67]:
torch.rand([3, 2]) @ torch.rand([2, 3])

tensor([[0.8518, 0.3749, 0.2801],
        [0.8762, 0.2739, 0.1395],
        [0.2595, 0.1094, 0.0790]])

In [68]:
torch.rand([2, 3]) @ torch.rand([3, 2])

tensor([[0.2295, 0.1103],
        [0.5921, 0.6943]])

In [69]:
a = torch.rand([4, 3])
a

tensor([[0.8082, 0.7396, 0.9430],
        [0.4692, 0.7127, 0.4501],
        [0.3833, 0.5511, 0.2562],
        [0.0925, 0.8504, 0.4969]])

In [70]:
b = a.T
b

tensor([[0.8082, 0.4692, 0.3833, 0.0925],
        [0.7396, 0.7127, 0.5511, 0.8504],
        [0.9430, 0.4501, 0.2562, 0.4969]])

In [71]:
a.shape, b.shape

(torch.Size([4, 3]), torch.Size([3, 4]))

In [72]:
b.T

tensor([[0.8082, 0.7396, 0.9430],
        [0.4692, 0.7127, 0.4501],
        [0.3833, 0.5511, 0.2562],
        [0.0925, 0.8504, 0.4969]])

In [73]:
torch.mm(a, a.T)

tensor([[2.0894, 1.3308, 0.9590, 1.1723],
        [1.3308, 0.9307, 0.6879, 0.8732],
        [0.9590, 0.6879, 0.5163, 0.6314],
        [1.1723, 0.8732, 0.6314, 0.9787]])

### Tensor aggregation

In [74]:
tensor = torch.arange(0, 100, 10)
tensor, tensor.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [75]:
torch.min(tensor), tensor.min()

(tensor(0), tensor(0))

In [76]:
torch.max(tensor), tensor.max()

(tensor(90), tensor(90))

In [77]:
torch.mean(tensor.type(torch.float32)), tensor.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [78]:
torch.sum(tensor), tensor.sum()

(tensor(450), tensor(450))

### Finiding positions

In [79]:
tensor

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [80]:
torch.argmax(tensor), tensor.argmax()

(tensor(9), tensor(9))

In [81]:
tensor[tensor.argmax()]

tensor(90)

In [82]:
torch.argmin(tensor), tensor.argmin()

(tensor(0), tensor(0))

In [83]:
tensor[torch.argmin(tensor)]

tensor(0)

### Reshaping, starcking, squeezing and unsqueezing tensors

In [84]:
a = torch.rand(size=[3, 5])
a

tensor([[0.7018, 0.7623, 0.7824, 0.0432, 0.9030],
        [0.3172, 0.4176, 0.5759, 0.6326, 0.3480],
        [0.5093, 0.4699, 0.9838, 0.1216, 0.2902]])

In [85]:
a.shape

torch.Size([3, 5])

In [86]:
a_reshaped = a.reshape(1, 15)
a_reshaped, a_reshaped.shape

(tensor([[0.7018, 0.7623, 0.7824, 0.0432, 0.9030, 0.3172, 0.4176, 0.5759, 0.6326,
          0.3480, 0.5093, 0.4699, 0.9838, 0.1216, 0.2902]]),
 torch.Size([1, 15]))

In [87]:
a_reshaped = a.reshape(5, 3)
a_reshaped, a_reshaped.shape

(tensor([[0.7018, 0.7623, 0.7824],
         [0.0432, 0.9030, 0.3172],
         [0.4176, 0.5759, 0.6326],
         [0.3480, 0.5093, 0.4699],
         [0.9838, 0.1216, 0.2902]]),
 torch.Size([5, 3]))

In [88]:
a_reshaped = a.reshape(15, 1)
a_reshaped, a_reshaped.shape

(tensor([[0.7018],
         [0.7623],
         [0.7824],
         [0.0432],
         [0.9030],
         [0.3172],
         [0.4176],
         [0.5759],
         [0.6326],
         [0.3480],
         [0.5093],
         [0.4699],
         [0.9838],
         [0.1216],
         [0.2902]]),
 torch.Size([15, 1]))

In [89]:
b = a.view(3, 5) # chaning b changes a - a view of a tensor shares the same memory as the original input
b, b.shape

(tensor([[0.7018, 0.7623, 0.7824, 0.0432, 0.9030],
         [0.3172, 0.4176, 0.5759, 0.6326, 0.3480],
         [0.5093, 0.4699, 0.9838, 0.1216, 0.2902]]),
 torch.Size([3, 5]))

In [90]:
b[0][0] = 19
a, b

(tensor([[19.0000,  0.7623,  0.7824,  0.0432,  0.9030],
         [ 0.3172,  0.4176,  0.5759,  0.6326,  0.3480],
         [ 0.5093,  0.4699,  0.9838,  0.1216,  0.2902]]),
 tensor([[19.0000,  0.7623,  0.7824,  0.0432,  0.9030],
         [ 0.3172,  0.4176,  0.5759,  0.6326,  0.3480],
         [ 0.5093,  0.4699,  0.9838,  0.1216,  0.2902]]))

In [91]:
a_stacked = torch.stack([a, a, a, a], dim=0)
a_stacked

tensor([[[19.0000,  0.7623,  0.7824,  0.0432,  0.9030],
         [ 0.3172,  0.4176,  0.5759,  0.6326,  0.3480],
         [ 0.5093,  0.4699,  0.9838,  0.1216,  0.2902]],

        [[19.0000,  0.7623,  0.7824,  0.0432,  0.9030],
         [ 0.3172,  0.4176,  0.5759,  0.6326,  0.3480],
         [ 0.5093,  0.4699,  0.9838,  0.1216,  0.2902]],

        [[19.0000,  0.7623,  0.7824,  0.0432,  0.9030],
         [ 0.3172,  0.4176,  0.5759,  0.6326,  0.3480],
         [ 0.5093,  0.4699,  0.9838,  0.1216,  0.2902]],

        [[19.0000,  0.7623,  0.7824,  0.0432,  0.9030],
         [ 0.3172,  0.4176,  0.5759,  0.6326,  0.3480],
         [ 0.5093,  0.4699,  0.9838,  0.1216,  0.2902]]])

In [92]:
a_stacked = torch.stack([a, a, a, a], dim=1)
a_stacked

tensor([[[19.0000,  0.7623,  0.7824,  0.0432,  0.9030],
         [19.0000,  0.7623,  0.7824,  0.0432,  0.9030],
         [19.0000,  0.7623,  0.7824,  0.0432,  0.9030],
         [19.0000,  0.7623,  0.7824,  0.0432,  0.9030]],

        [[ 0.3172,  0.4176,  0.5759,  0.6326,  0.3480],
         [ 0.3172,  0.4176,  0.5759,  0.6326,  0.3480],
         [ 0.3172,  0.4176,  0.5759,  0.6326,  0.3480],
         [ 0.3172,  0.4176,  0.5759,  0.6326,  0.3480]],

        [[ 0.5093,  0.4699,  0.9838,  0.1216,  0.2902],
         [ 0.5093,  0.4699,  0.9838,  0.1216,  0.2902],
         [ 0.5093,  0.4699,  0.9838,  0.1216,  0.2902],
         [ 0.5093,  0.4699,  0.9838,  0.1216,  0.2902]]])

In [93]:
b = torch.rand(size=[1, 1, 3])
b, b.shape

(tensor([[[0.5262, 0.7944, 0.8516]]]), torch.Size([1, 1, 3]))

In [94]:
c = b.squeeze()
c, c.shape

(tensor([0.5262, 0.7944, 0.8516]), torch.Size([3]))

In [95]:
d = c.unsqueeze(dim=0).unsqueeze(dim=0)
d, d.shape

(tensor([[[0.5262, 0.7944, 0.8516]]]), torch.Size([1, 1, 3]))

In [96]:
e = c.unsqueeze(dim=-2)
e, e.shape

(tensor([[0.5262, 0.7944, 0.8516]]), torch.Size([1, 3]))

In [97]:
f = c.unsqueeze(dim=1)
f, f.shape

(tensor([[0.5262],
         [0.7944],
         [0.8516]]),
 torch.Size([3, 1]))

In [98]:
y = torch.rand(size=(224, 224, 3))
y, y.shape

(tensor([[[0.9560, 0.1472, 0.0540],
          [0.6535, 0.8789, 0.2193],
          [0.4463, 0.4453, 0.7468],
          ...,
          [0.3648, 0.6559, 0.0393],
          [0.1103, 0.2761, 0.8908],
          [0.0525, 0.2096, 0.4359]],
 
         [[0.3786, 0.4748, 0.4636],
          [0.8022, 0.0172, 0.7232],
          [0.0809, 0.7284, 0.1472],
          ...,
          [0.7267, 0.7120, 0.8146],
          [0.1335, 0.8289, 0.7578],
          [0.7444, 0.9164, 0.5974]],
 
         [[0.5294, 0.2655, 0.9047],
          [0.9683, 0.9175, 0.2811],
          [0.2102, 0.3730, 0.4815],
          ...,
          [0.8609, 0.2696, 0.5803],
          [0.2135, 0.9165, 0.3753],
          [0.7968, 0.5198, 0.2858]],
 
         ...,
 
         [[0.9769, 0.6579, 0.1511],
          [0.3202, 0.3889, 0.6841],
          [0.4257, 0.2299, 0.3186],
          ...,
          [0.6443, 0.2674, 0.8013],
          [0.3691, 0.5701, 0.0628],
          [0.4623, 0.8319, 0.9833]],
 
         [[0.8517, 0.7823, 0.8436],
          [0

In [99]:
z = y.permute((2, 0, 1))
z, z.shape

(tensor([[[0.9560, 0.6535, 0.4463,  ..., 0.3648, 0.1103, 0.0525],
          [0.3786, 0.8022, 0.0809,  ..., 0.7267, 0.1335, 0.7444],
          [0.5294, 0.9683, 0.2102,  ..., 0.8609, 0.2135, 0.7968],
          ...,
          [0.9769, 0.3202, 0.4257,  ..., 0.6443, 0.3691, 0.4623],
          [0.8517, 0.6970, 0.5108,  ..., 0.9288, 0.1009, 0.7546],
          [0.2872, 0.9683, 0.2062,  ..., 0.6584, 0.7763, 0.5202]],
 
         [[0.1472, 0.8789, 0.4453,  ..., 0.6559, 0.2761, 0.2096],
          [0.4748, 0.0172, 0.7284,  ..., 0.7120, 0.8289, 0.9164],
          [0.2655, 0.9175, 0.3730,  ..., 0.2696, 0.9165, 0.5198],
          ...,
          [0.6579, 0.3889, 0.2299,  ..., 0.2674, 0.5701, 0.8319],
          [0.7823, 0.8195, 0.0184,  ..., 0.8579, 0.0430, 0.5597],
          [0.0024, 0.9397, 0.7993,  ..., 0.5520, 0.3999, 0.5293]],
 
         [[0.0540, 0.2193, 0.7468,  ..., 0.0393, 0.8908, 0.4359],
          [0.4636, 0.7232, 0.1472,  ..., 0.8146, 0.7578, 0.5974],
          [0.9047, 0.2811, 0.4815,  ...,

### Indexing

In [101]:
x = torch.arange(1, 10, 1)
x

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
y = x.reshape(1, 3, 3)
y

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [106]:
y[0, 0, 0], y[0, 0, 1], y[0, 0, 2]

(tensor(1), tensor(2), tensor(3))

In [108]:
y[0, 1]

tensor([4, 5, 6])

In [109]:
y[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [110]:
y[0, 1, :2]

tensor([4, 5])

In [112]:
y[0, 1, 1:]

tensor([5, 6])

In [113]:
y[0][0]

tensor([1, 2, 3])

In [114]:
y[0][1][1:]

tensor([5, 6])

In [116]:
y[0][0][0] = 10

In [118]:
y, x

(tensor([[[10,  2,  3],
          [ 4,  5,  6],
          [ 7,  8,  9]]]),
 tensor([10,  2,  3,  4,  5,  6,  7,  8,  9]))

In [122]:
y[:, :, 1]

tensor([[2, 5, 8]])

In [125]:
y[:, :, 0]

tensor([[10,  4,  7]])

In [127]:
y[0][0], y[0, 0, :]

(tensor([10,  2,  3]), tensor([10,  2,  3]))

In [131]:
y[0][2][-1]

tensor(9)

In [132]:
y[:, :, 2]

tensor([[3, 6, 9]])