# 00. PyTorch Fundamentals Exercises

## 1. Documentation reading
A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):

The documentation on torch.Tensor.

The documentation on torch.cuda.

## 2. Create a random tensor with shape `(7, 7)`

In [1]:
# Import torch
import torch

In [2]:
# Create random tensor
tensor_a = torch.rand(size=(7,7))
tensor_a

tensor([[0.4351, 0.7071, 0.0132, 0.4975, 0.3686, 0.1856, 0.5925],
        [0.7363, 0.8581, 0.8052, 0.0816, 0.0121, 0.9903, 0.0866],
        [0.1265, 0.2788, 0.6304, 0.7212, 0.0632, 0.4433, 0.4137],
        [0.3019, 0.7043, 0.3981, 0.7323, 0.9564, 0.8900, 0.0461],
        [0.0793, 0.2856, 0.5264, 0.2256, 0.7240, 0.3528, 0.5610],
        [0.2556, 0.8208, 0.3576, 0.0960, 0.3941, 0.4079, 0.7174],
        [0.7070, 0.1707, 0.6076, 0.2893, 0.8614, 0.8122, 0.4966]])

In [3]:
tensor_a.size(), tensor_a.shape, tensor_a.ndim

(torch.Size([7, 7]), torch.Size([7, 7]), 2)

## 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor)

In [4]:
# Create another random tensor
tensor_b = torch.rand(size=(1, 7))
tensor_b

tensor([[0.9994, 0.7252, 0.2502, 0.0716, 0.9645, 0.0925, 0.1046]])

In [5]:
# Perform matrix multiplication 
tensor_a @ tensor_b.T

tensor([[1.4213],
        [1.6776],
        [0.6833],
        [1.9741],
        [1.2238],
        [1.4399],
        [1.9610]])

In [6]:
# Perform matrix multiplication
tensor_b @ tensor_a

tensor([[1.1961, 1.8183, 1.3877, 1.0460, 1.2863, 1.5412, 1.4212]])

## 4. Set the random seed to `0` and do 2 & 3 over again

In [7]:
# Set manual seed
# Create two random tensors
torch.manual_seed(42)
tensor_a = torch.rand(size=(7, 7))

# Set manual seed
# Create two random tensors
torch.manual_seed(42)
tensor_b = torch.rand(size=(1, 7))

In [8]:
# Matrix multiply tensors
tensor_a @ tensor_b.T

tensor([[3.2618],
        [3.4084],
        [2.4866],
        [1.4525],
        [1.7079],
        [2.7291],
        [2.9204]])

In [9]:
# Matrix multiply tensors
tensor_b @ tensor_a

tensor([[3.0938, 2.7098, 2.7137, 2.4572, 2.0022, 2.6702, 1.5846]])

## 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one)

- If there is, set the GPU random seed to 1234.

In [10]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)

## 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed)

In [11]:
# Check for access to GPU
torch.cuda.is_available()

False

In [12]:
# Set manual seed
# Create two random tensors
torch.manual_seed(42)
tensor_a = torch.rand(size=(3, 2), device="mps")

# Set manual seed
# Create two random tensors
torch.manual_seed(42)
tensor_b = torch.rand(size=(3, 4), device="mps")

In [13]:
tensor_a.device, tensor_a

(device(type='mps', index=0),
 tensor([[0.8172, 0.5881],
         [0.5581, 0.7691],
         [0.3394, 0.4560]], device='mps:0'))

In [14]:
tensor_b.device, tensor_b

(device(type='mps', index=0),
 tensor([[8.1718e-01, 5.8811e-01, 5.5805e-01, 7.6914e-01],
         [3.3936e-01, 4.5596e-01, 6.7508e-01, 4.4060e-04],
         [4.0876e-01, 1.7912e-01, 5.9732e-01, 8.4722e-01]], device='mps:0'))

## 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors)

In [15]:
# Perform matmul on tensor_A and tensor_B
tensor_a.T @ tensor_b

tensor([[0.9959, 0.7958, 1.0355, 0.9163],
        [0.9280, 0.7782, 1.1198, 0.8390]], device='mps:0')

In [16]:
# Perform matmul on tensor_B and tensor_A
tensor_b.T @ tensor_a

tensor([[0.9959, 0.9280],
        [0.7958, 0.7782],
        [1.0355, 1.1198],
        [0.9163, 0.8390]], device='mps:0')

## 8. Find the maximum and minimum values of the output of 7

In [17]:
tensor_c = tensor_a.T @ tensor_b
tensor_d = tensor_b.T @ tensor_a

In [18]:
# Find min
torch.min(tensor_c), tensor_d.min()

(tensor(0.7782, device='mps:0'), tensor(0.7782, device='mps:0'))

In [19]:
# Find max
torch.max(tensor_c), tensor_d.max()

(tensor(1.1198, device='mps:0'), tensor(1.1198, device='mps:0'))

## 9. Find the maximum and minimum index values of the output of 7

In [20]:
# Find arg min
torch.argmin(tensor_c), tensor_d.argmin()

(tensor(5, device='mps:0'), tensor(3, device='mps:0'))

In [21]:
# Find arg max
torch.argmax(tensor_d), tensor_d.argmax()

(tensor(5, device='mps:0'), tensor(5, device='mps:0'))

## 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [22]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor = torch.rand(size=(1, 1, 1, 10))
tensor, tensor.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]))

In [23]:
# Remove single dimensions
new_tensor = tensor.squeeze()

# Remove single dimensions
new_tensor, new_tensor.shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))